Repository sematic-ai/sematic, pull requests merged in 2022-08, with the labels that each got.

#72 Baseline Grafana integration for log panels
  docs/SUMMARY.md
  docs/grafana.md
  docs/sematic-ui.md
  sematic/api/endpoints/auth.py
  sematic/api/endpoints/tests/test_auth.py
  sematic/api/tests/fixtures.py
  sematic/resolvers/worker.py
  sematic/ui/src/Payloads.tsx
  sematic/ui/src/addons/grafana/GrafanaPanel.tsx
  sematic/ui/src/components/DagTab.tsx
  sematic/ui/src/components/Docstring.tsx
  sematic/ui/src/components/Exception.tsx
  sematic/ui/src/components/RunPanel.tsx
  sematic/ui/src/components/RunTabs.tsx
  sematic/ui/src/index.tsx
  sematic/user_settings.py
Labels: enhancement, ui

#79 New `Link` type to display buttons in the UI
  docs/SUMMARY.md
  docs/types.md
  sematic/types/BUILD
  sematic/types/__init__.py
  sematic/types/types/BUILD
  sematic/types/types/link.py
  sematic/types/types/tests/BUILD
  sematic/types/types/tests/test_link.py
  sematic/ui/src/types/Types.tsx
Labels: enhancement, ui

#81 Sematic vs updates
  docs/README.md
  docs/sematic-vs.md
Labels: documentation

#84 Support Python 3.8
  WORKSPACE
  docs/source/glow.types.types.rst
  sematic/__init__.py
  sematic/calculator.py
  sematic/cli/run.py
  sematic/examples/add/pipeline.py
  sematic/future.py
  sematic/future_operators/getitem.py
  sematic/future_operators/iter.py
  sematic/types/BUILD
  sematic/types/__init__.py
  sematic/types/casting.py
  sematic/types/registry.py
  sematic/types/serialization.py
  sematic/types/tests/BUILD
  sematic/types/tests/test_casting.py
  sematic/types/tests/test_generic.py
  sematic/types/tests/test_init.py
  sematic/types/types/BUILD
  sematic/types/types/dataclass.py
  sematic/types/types/float_in_range.py
  sematic/types/types/tests/BUILD
  sematic/types/types/tests/test_float_in_range.py
Labels: enhancement

#80 Version compatibility check
  docs/changelog.md
  sematic/BUILD
  sematic/__init__.py
  sematic/api/BUILD
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/auth.py
  sematic/api/endpoints/meta.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_auth.py
  sematic/api/endpoints/tests/test_meta.py
  sematic/api/server.py
  sematic/api/tests/fixtures.py
  sematic/api_client.py
  sematic/tests/BUILD
  sematic/tests/test_api_client.py
  sematic/types/types/pandas/dataframe.py
  sematic/ui/src/index.tsx
  sematic/utils/BUILD
  sematic/utils/retry.py
  sematic/versions.py
Labels: enhancement

#99 Enable bazel usage with multiple hermetic python versions
  .circleci/config.yml
  BUILD
  WORKSPACE
  sematic/BUILD
  sematic/api/BUILD
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/tests/BUILD
  sematic/api/tests/BUILD
  sematic/cli/BUILD
  sematic/cli/tests/BUILD
  sematic/db/BUILD
  sematic/db/models/BUILD
  sematic/db/tests/BUILD
  sematic/resolvers/BUILD
  sematic/tests/BUILD
  sematic/tests/test_38_interpreter.py
  sematic/tests/test_39_interpreter.py
  sematic/types/BUILD
  sematic/types/types/pandas/tests/BUILD
  sematic/types/types/pytorch/BUILD
  sematic/types/types/snowflake/tests/BUILD
  stub.py.tpl
  tools/BUILD
  tools/build_rules/prelude_bazel
  tools/jupyter/BUILD
  tools/sematic_rules.bzl
  tools/sematic_wheel_rule.bzl
Labels: enhancement

#91 Public API to retrieve artifact values
  docs/SUMMARY.md
  docs/artifacts.md
  docs/images/artifactId.png
  sematic/BUILD
  sematic/api/endpoints/artifacts.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_artifacts.py
  sematic/api_client.py
  sematic/client.py
  sematic/db/queries.py
  sematic/db/tests/BUILD
  sematic/db/tests/fixtures.py
  sematic/db/tests/test_queries.py
  sematic/tests/BUILD
  sematic/tests/fixtures.py
  sematic/tests/test_api_client.py
  sematic/tests/test_client.py
  sematic/ui/src/components/Artifacts.tsx
Labels: documentation, enhancement, ui

#101 Make versions consistent
  BUILD
  docs/changelog.md
  sematic/BUILD
  sematic/tests/BUILD
  sematic/tests/test_versions.py
  sematic/versions.py
  sematic/wheel_version.bzl
  tools/sematic_rules.bzl
Labels: housekeeping

#105 Add debugpy as automatically available
  developer-docs/tips-for-bazel.md
  docs/contributor-guide.md
  requirements/requirements.in
  requirements/requirements.txt
  tools/pytest_runner.py
  tools/sematic_rules.bzl
Labels: housekeeping

#103 Root run deep linking
  sematic/ui/src/components/Notes.tsx
  sematic/ui/src/components/NotesPanel.tsx
  sematic/ui/src/components/PipelineBar.tsx
  sematic/ui/src/index.tsx
  sematic/ui/src/pipelines/PipelineView.tsx
Labels: enhancement, ui

#106 Make it so we actually get log messages from loggers
  sematic/api/server.py
Labels: enhancement

#104 Resolutions hookup
  sematic/BUILD
  sematic/abstract_calculator.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_runs.py
  sematic/api_client.py
  sematic/calculator.py
  sematic/cli/BUILD
  sematic/db/models/resolution.py
  sematic/db/queries.py
  sematic/db/tests/test_queries.py
  sematic/examples/add/pipeline.py
  sematic/resolvers/BUILD
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/state_machine_resolver.py
  sematic/resolvers/tests/BUILD
  sematic/resolvers/tests/test_cloud_resolver.py
  sematic/resolvers/tests/test_local_resolver.py
  sematic/resolvers/tests/test_worker.py
  sematic/resolvers/worker.py
  sematic/tests/BUILD
  sematic/tests/test_calculator.py
Labels: enhancement

#116 Improve empty list handling
  sematic/ui/src/types/Types.tsx
Labels: bug

#120 Enable api override url
  docs/deploy.md
  docs/get-started.md
  sematic/config.py
  sematic/resolvers/cloud_resolver.py
  sematic/user_settings.py
Labels: enhancement

#121 Add ability to change config dir with env var
  docs/cli.md
  sematic/config_dir.py
  sematic/tests/BUILD
  sematic/tests/fixtures.py
  sematic/tests/test_config_dir.py
Labels: enhancement
