Repository sematic-ai/sematic, pull requests merged in 2022-11, with the labels that each got.

#283 Fix dead links in the documentation
  docs/SUMMARY.md
  docs/bigquery.md
  docs/dataflow.md
  docs/dbt.md
  docs/integrations.md
  docs/redshift.md
  docs/slack.md
Labels: documentation

#284 Update contributing guide with good first issues
  docs/contributor-guide.md
Labels: documentation

#281 Fix five bugs
  sematic/db/models/factories.py
  sematic/db/models/tests/test_factories.py
  sematic/ui/src/components/Notes.tsx
  sematic/ui/src/components/PipelinePanels.tsx
  sematic/ui/src/components/RunPanel.tsx
  sematic/ui/src/components/RunTabs.tsx
  sematic/ui/src/components/SnackBarProvider.tsx
Labels: bug, ui

#285 Add PyPi links to the changelog
  docs/changelog.md
  sematic/tests/test_versions.py
Labels: documentation

#287 Bump versions for 0.19.1
  docs/changelog.md
  helm/sematic/values.yaml
  sematic/versions.py
  sematic/wheel_version.bzl
Labels: release

#288 Add the "Third-party" import section to isort configs
  pyproject.toml
  sematic/api/app.py
  sematic/api/endpoints/events.py
  sematic/api/endpoints/tests/test_artifacts.py
  sematic/api/tests/fixtures.py
  sematic/api_client.py
  sematic/cli/tests/test_main.py
  sematic/container_images.py
  sematic/db/models/artifact.py
  sematic/db/models/base.py
  sematic/db/models/note.py
  sematic/db/models/resolution.py
  sematic/db/models/run.py
  sematic/db/models/tests/test_factories.py
  sematic/db/models/tests/test_resolution.py
  sematic/examples/dynamic_graph/pipeline.py
  sematic/examples/liver_cirrhosis/train.py
  sematic/examples/mnist/pytorch/train_eval.py
  sematic/examples/titanic_survival_prediction/plots.py
  sematic/resolvers/tests/fixtures.py
  sematic/resolvers/tests/test_resource_requirements.py
  sematic/resolvers/tests/test_silent_resolver.py
  sematic/resolvers/tests/test_worker.py
  sematic/scheduling/tests/test_job_scheduler.py
  sematic/scheduling/tests/test_kubernetes.py
  sematic/testing/tests/test_mock_funcs.py
  sematic/tests/test_38_interpreter.py
  sematic/tests/test_39_interpreter.py
  sematic/tests/test_api_client.py
  sematic/tests/test_config_dir.py
  sematic/tests/test_log_reader.py
  sematic/tests/test_retry_settings.py
  sematic/tests/test_versions.py
  sematic/types/tests/test_registry.py
  sematic/types/tests/test_type.py
  sematic/types/types/matplotlib/__init__.py
  sematic/types/types/pandas/__init__.py
  sematic/types/types/pandas/dataframe.py
  sematic/types/types/pandas/tests/test_dataframe.py
  sematic/types/types/plotly/__init__.py
  sematic/types/types/pytorch/__init__.py
  sematic/types/types/snowflake/snowflake_table.py
  sematic/types/types/tests/test_enum.py
  sematic/types/types/tests/test_integer.py
  sematic/user_settings.py
  sematic/utils/git.py
Labels: housekeeping

#291 Fix Python migration UPDATE SQL statement
  sematic/db/migrations/20221019225916_migrate_container_image_uris.py
Labels: bug, db

#290 Fix vararg error message broken link
  sematic/calculator.py
Labels: bug

#292 Bump versions for 0.19.2
  docs/changelog.md
  helm/sematic/values.yaml
  sematic/versions.py
  sematic/wheel_version.bzl
Labels: release

#305 Fix mypy issues on main
  sematic/api/wsgi.py
  sematic/calculator.py
  sematic/tests/test_calculator.py
  sematic/tests/test_client.py
Labels: bug, housekeeping, ci, testing

#304 Fix various migration script issues
  sematic/db/migrations/20220610234559_create_notes_table.sql
  sematic/db/migrations/20220930014400_migrate_exception_data.py
Labels: bug, db

#312 Script that switches between profiles
  developer-docs/README.md
  tools/BUILD
  tools/switch-settings.sh
Labels: enhancement, tech debt

#220 Add datetime class and basic visualization
  sematic/types/BUILD
  sematic/types/__init__.py
  sematic/types/types/BUILD
  sematic/types/types/datetime.py
  sematic/types/types/tests/BUILD
  sematic/types/types/tests/test_datetime.py
  sematic/ui/package-lock.json
  sematic/ui/package.json
  sematic/ui/src/types/Types.tsx
Labels: enhancement, types

#323 Temporarily remove drop column from up migrations
  sematic/db/migrations/20221004183943_remove_exception_from_runs.sql
  sematic/versions.py
Labels: bug, db

#326 Refactor User Settings in preparation for Server Settings split
  docs/snowflake.md
  sematic/BUILD
  sematic/api/BUILD
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/auth.py
  sematic/api/endpoints/meta.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_auth.py
  sematic/api/endpoints/tests/test_meta.py
  sematic/api/server.py
  sematic/api/tests/BUILD
  sematic/api/tests/fixtures.py
  sematic/api_client.py
  sematic/cli/BUILD
  sematic/cli/cli.py
  sematic/cli/examples_utils.py
  sematic/cli/new.py
  sematic/cli/process_utils.py
  sematic/cli/run.py
  sematic/cli/settings.py
  sematic/cli/start.py
  sematic/cli/tests/BUILD
  sematic/cli/tests/test_main.py
  sematic/config/BUILD
  sematic/config/__init__.py
  sematic/config/config.py
  sematic/config/config_dir.py
  sematic/config/tests/BUILD
  sematic/config/tests/__init__.py
  sematic/config/tests/test_config_dir.py
  sematic/config/tests/test_user_settings.py
  sematic/config/user_settings.py
  sematic/db/BUILD
  sematic/db/db.py
  sematic/db/migrate.py
  sematic/resolvers/BUILD
  sematic/resolvers/local_resolver.py
  sematic/resolvers/log_streamer.py
  sematic/scheduling/BUILD
  sematic/scheduling/kubernetes.py
  sematic/scheduling/tests/test_kubernetes.py
  sematic/storage.py
  sematic/tests/BUILD
  sematic/tests/test_api_client.py
  sematic/types/types/matplotlib/BUILD
  sematic/types/types/matplotlib/figure.py
  sematic/types/types/snowflake/BUILD
  sematic/types/types/snowflake/snowflake_table.py
  sematic/user_settings.py
Labels: cli, tech debt

#332 Streamlining handling of artifacts in `LocalResolver` in order to fix a re-run bug
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/state_machine_resolver.py
  sematic/tests/test_graph.py
Labels: bug, enhancement

#318 Attempt to fix _make_list reruns
  sematic/BUILD
  sematic/calculator.py
  sematic/graph.py
  sematic/resolvers/BUILD
  sematic/resolvers/tests/BUILD
  sematic/resolvers/tests/test_type_utils.py
  sematic/resolvers/type_utils.py
Labels: bug

#339 Fix cli command arg passing
  sematic/cli/run.py
Labels: bug, cli, examples

#340 Lint the source code on main
  sematic/graph.py
  sematic/tests/test_graph.py
Labels: housekeeping

#325 #310 Fixes the multi-line docstring rendering.
  sematic/db/models/run.py
  sematic/db/models/tests/test_run.py
Labels: bug, ui

#335 Make server not start if migration fails
  docker/Dockerfile.server
Labels: bug, db

#327 Bump versions for 0.20.0
  docs/changelog.md
  helm/sematic/values.yaml
  sematic/versions.py
  sematic/wheel_version.bzl
Labels: release

#341 Remove deprecated abstractproperty
  sematic/abstract_calculator.py
Labels: housekeeping

#330 Split user and server settings
  developer-docs/README.md
  docs/changelog.md
  docs/cli.md
  docs/deploy.md
  docs/snowflake.md
  sematic/BUILD
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/auth.py
  sematic/api/endpoints/meta.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_auth.py
  sematic/api/endpoints/tests/test_meta.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/api/tests/BUILD
  sematic/api/tests/fixtures.py
  sematic/api_client.py
  sematic/cli/BUILD
  sematic/cli/settings.py
  sematic/config/BUILD
  sematic/config/config.py
  sematic/config/config_dir.py
  sematic/config/server_settings.py
  sematic/config/settings.py
  sematic/config/tests/test_user_settings.py
  sematic/config/user_settings.py
  sematic/scheduling/BUILD
  sematic/scheduling/kubernetes.py
  sematic/scheduling/tests/BUILD
  sematic/scheduling/tests/test_kubernetes.py
  sematic/storage.py
  tools/switch-settings.sh
Labels: cli, tech debt

#353 Add support to subclasses of `ABCMeta`
  sematic/types/registry.py
Labels: types

#352 Fix Union serdes
  docs/changelog.md
  sematic/types/types/tests/BUILD
  sematic/types/types/tests/test_dict.py
  sematic/types/types/tests/test_union.py
  sematic/types/types/union.py
Labels: tech debt, types

#348 CLI for reading logs
  docs/changelog.md
  sematic/BUILD
  sematic/cli/BUILD
  sematic/cli/cli.py
  sematic/cli/logs.py
  sematic/cli/main.py
  sematic/cli/tests/BUILD
  sematic/cli/tests/test_logs.py
  sematic/log_reader.py
  sematic/tests/test_log_reader.py
Labels: observability, ci

#357 Chance/refactor view redirection
  sematic/ui/src/Payloads.tsx
  sematic/ui/src/components/PipelineBar.tsx
  sematic/ui/src/hooks/pipelineHooks.ts
  sematic/ui/src/index.tsx
  sematic/ui/src/pipelines/PipelineRunView.tsx
  sematic/ui/src/pipelines/PipelineView.tsx
Labels: ui, housekeeping

#344 Use JSON payload instead of figure to support matplotlib figures
  mypy.ini
  requirements/requirements.in
  requirements/requirements.txt
  sematic/BUILD
  sematic/types/types/matplotlib/BUILD
  sematic/types/types/matplotlib/figure.py
  sematic/ui/package-lock.json
  sematic/ui/package.json
  sematic/ui/src/hooks/useMatplotLib.ts
  sematic/ui/src/types/Types.tsx
  sematic/ui/src/vendor/types/mpld3.d.ts
  sematic/ui/src/vendor/types/plotly.js-cartesian-dist.d.ts
  sematic/ui/src/vendor/types/react-app-env.d.ts
Labels: bug, ui, db

#360 Fixed a issue caused by variable renaming.
  sematic/ui/src/hooks/pipelineHooks.ts
Labels: bug, ui

#358 Update Release Docs for new Helm Charts
  developer-docs/README.md
  helm/sematic-server/values.yaml
Labels: documentation, infrastructure

#359 Bump versions for 0.20.1 and introduce a Special Release Procedure
  developer-docs/README.md
  docs/changelog.md
  helm/sematic-server/Chart.yaml
  helm/sematic-server/values.yaml
  sematic/versions.py
  sematic/wheel_version.bzl
Labels: documentation, release
