Repository sematic-ai/sematic, pull requests merged in 2022-12, with the labels that each got.

#371 Update UI package versions
  sematic/ui/package-lock.json
Labels: ui, housekeeping

#370 Fix example pipelines' README files rendering
  docs/changelog.md
  sematic/cli/examples_utils.py
  sematic/cli/tests/test_new.py
  sematic/examples/README.md
  sematic/examples/add/README.md
  sematic/examples/dynamic_graph/README.md
  sematic/examples/liver_cirrhosis/README.md
  sematic/examples/mnist/pytorch/README.md
  sematic/examples/template/README.md
  sematic/examples/testing_pipeline/README.md
  sematic/examples/titanic_survival_prediction/README.md
  tools/sematic_rules.bzl
Labels: bug, documentation, examples

#375 Enable configurable worker sa
  docs/changelog.md
  helm/sematic-server/Chart.yaml
  helm/sematic-server/templates/configmap.yaml
  helm/sematic-server/templates/serviceaccount.yaml
  helm/sematic-server/values.yaml
  sematic/config/server_settings.py
  sematic/scheduling/kubernetes.py
  sematic/scheduling/tests/test_kubernetes.py
Labels: enhancement, security

#362 Refactor the hook usage on pipeline related scenarios
  sematic/ui/src/Home.tsx
  sematic/ui/src/components/PipelineBar.tsx
  sematic/ui/src/components/RunList.tsx
  sematic/ui/src/hooks/httpHooks.ts
  sematic/ui/src/hooks/pipelineHooks.ts
  sematic/ui/src/pipelines/PipelineIndex.tsx
  sematic/ui/src/pipelines/PipelineView.tsx
Labels: enhancement, ui, housekeeping

#379 [bugfix] Missing broadcasts upon server-side run save
  docs/changelog.md
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/test_runs.py
Labels: bug

#380 [bugfix] Inline future status were not being updated by `CloudResolver` prior to executing
  sematic/resolvers/cloud_resolver.py
Labels: bug

#381 Update Future docstrings and properties validation
  sematic/BUILD
  sematic/calculator.py
  sematic/future.py
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
  sematic/tests/BUILD
  sematic/tests/test_future.py
Labels: documentation

#389 Add missing migration script reference
  sematic/db/schema.sql.sqlite
Labels: bug, db

#367 Gets rid of passing down `changeRootRunId`
  sematic/ui/src/components/Notes.tsx
  sematic/ui/src/components/NotesPanel.tsx
  sematic/ui/src/components/PipelineBar.tsx
  sematic/ui/src/components/PipelinePanels.tsx
  sematic/ui/src/hooks/pipelineHooks.ts
  sematic/ui/src/pipelines/PipelineRunView.tsx
Labels: ui, housekeeping

#366 Simplify logs processing logic #354
  sematic/ui/src/components/LogPanel.tsx
  sematic/ui/src/components/ScrollingLogView.tsx
  sematic/ui/src/hooks/httpHooks.ts
  sematic/ui/src/hooks/logHooks.ts
  sematic/ui/src/utils.tsx
Labels: ui, housekeeping

#324 add enum visualization and chip component
  sematic/ui/src/types/Types.tsx
Labels: enhancement, ui

#397 Makes RunID links more explicit visually
  sematic/ui/src/components/Notes.tsx
  sematic/ui/src/hooks/pipelineHooks.ts
Labels: bug, ui

#399 Add back worker url override
  helm/sematic-server/templates/configmap.yaml
  sematic/scheduling/BUILD
  sematic/scheduling/kubernetes.py
  sematic/scheduling/tests/test_kubernetes.py
Labels: bug, infrastructure

#390 Expose the Cloned Run ID in the UI
  sematic/abstract_future.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/cli/logs.py
  sematic/cli/tests/test_logs.py
  sematic/db/migrations/20221212110018_add_original_run_id.sql
  sematic/db/models/factories.py
  sematic/db/models/run.py
  sematic/db/schema.sql.sqlite
  sematic/db/tests/fixtures.py
  sematic/graph.py
  sematic/log_reader.py
  sematic/tests/test_graph.py
  sematic/tests/test_log_reader.py
  sematic/ui/src/Models.tsx
  sematic/ui/src/Payloads.tsx
  sematic/ui/src/components/RunPanel.tsx
  sematic/ui/src/components/ScrollingLogView.tsx
  sematic/ui/src/hooks/logHooks.ts
Labels: enhancement, wip, ui, db

#406 Allow multi-domain auth
  sematic/api/endpoints/auth.py
  sematic/api/endpoints/tests/test_auth.py
Labels: enhancement, security

#404 Future cache key module
  sematic/abstract_future.py
  sematic/caching/BUILD
  sematic/caching/__init__.py
  sematic/caching/caching.py
  sematic/caching/git.py
  sematic/caching/tests/BUILD
  sematic/caching/tests/__init__.py
  sematic/caching/tests/test_caching.py
  sematic/calculator.py
  sematic/db/models/BUILD
  sematic/db/models/factories.py
  sematic/graph.py
  sematic/resolvers/tests/test_local_resolver.py
  sematic/tests/test_graph.py
  sematic/utils/BUILD
  sematic/utils/git.py
  sematic/utils/hashing.py
  sematic/utils/json.py
  sematic/utils/tests/BUILD
  sematic/utils/tests/test_hashing.py
Labels: enhancement

#396 [1/N] `AbstractPlugin`
  docs/changelog.md
  sematic/BUILD
  sematic/abstract_plugin.py
  sematic/api/BUILD
  sematic/api/endpoints/tests/test_artifacts.py
  sematic/api/server.py
  sematic/api/tests/fixtures.py
  sematic/api_client.py
  sematic/cli/settings.py
  sematic/config/BUILD
  sematic/config/server_settings.py
  sematic/config/settings.py
  sematic/config/tests/BUILD
  sematic/config/tests/fixtures.py
  sematic/config/tests/test_server_settings.py
  sematic/config/tests/test_settings.py
  sematic/config/tests/test_user_settings.py
  sematic/config/user_settings.py
  sematic/db/migrate.py
  sematic/db/migrations/20221208183307_create_server_settings_file.py
  sematic/db/migrations/20221214142609_plugin_settings_file.py
  sematic/db/schema.sql.sqlite
  sematic/tests/BUILD
  sematic/tests/test_abstract_plugin.py
  sematic/versions.py
Labels: enhancement

#391 Implements the pull down to trigger logs fetch function
  sematic/ui/src/components/LogPanel.tsx
  sematic/ui/src/components/ScrollingLogView.tsx
  sematic/ui/src/hooks/httpHooks.ts
  sematic/ui/src/hooks/scrollingHooks.ts
  sematic/ui/src/hooks/setTimeoutHooks.ts
Labels: ui, housekeeping

#402 external resource api: within-single-func implementation
  sematic/BUILD
  sematic/api/endpoints/tests/test_runs.py
  sematic/calculator.py
  sematic/examples/testing_pipeline/BUILD
  sematic/examples/testing_pipeline/__main__.py
  sematic/examples/testing_pipeline/pipeline.py
  sematic/examples/testing_pipeline/requirements.txt
  sematic/external_resource.py
  sematic/future_context.py
  sematic/resolver.py
  sematic/resolvers/BUILD
  sematic/resolvers/abstract_resource_manager.py
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/resource_managers/BUILD
  sematic/resolvers/resource_managers/in_memory_manager.py
  sematic/resolvers/silent_resolver.py
  sematic/resolvers/tests/BUILD
  sematic/resolvers/tests/fixtures.py
  sematic/resolvers/tests/test_silent_resolver.py
  sematic/resolvers/tests/test_worker.py
  sematic/resolvers/worker.py
  sematic/tests/BUILD
  sematic/tests/test_external_resource.py
  sematic/utils/exceptions.py
Labels: enhancement, types

#415 [bugfix] Remove version from settings
  sematic/config/settings.py
  sematic/config/tests/test_settings.py
Labels: bug

#410 [1/2] Reactors the state management of Pipeline scenarios
  sematic/ui/src/components/MenuPanel.tsx
  sematic/ui/src/components/NotesPanel.tsx
  sematic/ui/src/components/PipelineBar.tsx
  sematic/ui/src/components/PipelinePanels.tsx
  sematic/ui/src/components/ReactFlowDag.tsx
  sematic/ui/src/components/RunPanel.tsx
  sematic/ui/src/components/RunTree.tsx
  sematic/ui/src/components/utils/typings.ts
  sematic/ui/src/hooks/pipelineHooks.ts
  sematic/ui/src/index.tsx
  sematic/ui/src/pipelines/PipelinePanelsContext.tsx
  sematic/ui/src/pipelines/PipelineRunView.tsx
  sematic/ui/src/pipelines/PipelineRunViewContext.tsx
  sematic/ui/src/pipelines/PipelineView.tsx
Labels: ui, housekeeping

#419 Fix missing requirement for example testing pipeline
  sematic/examples/testing_pipeline/BUILD
Labels: bug, examples

#420 Avoid Artifact overwrite
  sematic/db/models/artifact.py
  sematic/db/queries.py
  sematic/db/tests/fixtures.py
  sematic/db/tests/test_queries.py
Labels: bug, db, types

#422 Fix env var override for settings
  sematic/config/settings.py
  sematic/config/tests/BUILD
  sematic/config/tests/test_settings.py
  sematic/db/migrations/20221214142609_plugin_settings_file.py
Labels: bug

#407 [2/N] Storage plug-ins: `MemoryStorage`, `LocalStorage`, and `S3Storage`
  sematic/abstract_plugin.py
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/artifacts.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_artifacts.py
  sematic/config/settings.py
  sematic/db/migrations/20221219145906_migrate_s3_bucket_setting.py
  sematic/plugins/BUILD
  sematic/plugins/__init__.py
  sematic/plugins/abstract_storage.py
  sematic/plugins/storage/BUILD
  sematic/plugins/storage/__init__.py
  sematic/plugins/storage/local_storage.py
  sematic/plugins/storage/memory_storage.py
  sematic/plugins/storage/s3_storage.py
  sematic/plugins/storage/tests/BUILD
  sematic/plugins/storage/tests/test_local_storage.py
  sematic/plugins/storage/tests/test_memory_storage.py
  sematic/plugins/storage/tests/test_s3_storage.py
Labels: enhancement
