Repository sematic-ai/sematic, pull requests merged in 2022-07, with the labels that each got.

#59 Docker image to deploy server in cloud instance
  Dockerfile
  Makefile
  sematic/config.py
  sematic/db/BUILD
  sematic/db/migrate.py
  sematic/db/tests/BUILD
  sematic/db/tests/fixtures.py
  sematic/db/tests/test_migrate.py
Labels: enhancement

#60 Rename credentials to settings and remove app layer
  docs/changelog.md
  docs/cli.md
  docs/snowflake.md
  sematic/BUILD
  sematic/cli/BUILD
  sematic/cli/credentials.py
  sematic/cli/main.py
  sematic/cli/settings.py
  sematic/config.py
  sematic/credentials.py
  sematic/tests/BUILD
  sematic/tests/test_credentials.py
  sematic/tests/test_user_settings.py
  sematic/types/types/snowflake/BUILD
  sematic/types/types/snowflake/snowflake_table.py
  sematic/types/types/snowflake/tests/test_snowflake_table.py
  sematic/user_settings.py
Labels: enhancement

#61 Save graph via the API instead of directly to the DB
  Dockerfile
  Makefile
  sematic/BUILD
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/notes.py
  sematic/api/endpoints/request_parameters.py
  sematic/api/endpoints/runs.py
  sematic/api/server.py
  sematic/api_client.py
  sematic/cli/cli.py
  sematic/config.py
  sematic/config_dir.py
  sematic/db/migrate.py
  sematic/db/models/factories.py
  sematic/db/models/json_encodable_mixin.py
  sematic/db/models/run.py
  sematic/db/models/tests/test_run.py
  sematic/db/queries.py
  sematic/db/tests/test_queries.py
  sematic/resolvers/BUILD
  sematic/resolvers/local_resolver.py
  sematic/resolvers/tests/test_local_resolver.py
  sematic/tests/test_user_settings.py
  sematic/user_settings.py
Labels: enhancement

#62 Support for getitem and iter on futures
  docs/changelog.md
  docs/future-algebra.md
  requirements/ci-requirements.txt
  sematic/BUILD
  sematic/__init__.py
  sematic/future_operators/BUILD
  sematic/future_operators/__init__.py
  sematic/future_operators/getitem.py
  sematic/future_operators/iter.py
  sematic/future_operators/tests/BUILD
  sematic/future_operators/tests/test_getitem.py
  sematic/future_operators/tests/test_iter.py
  sematic/tests/test_future.py
Labels: enhancement

#64 Fixes Timestamp JSON serialization by defaulting to `str`
  sematic/db/models/factories.py
  sematic/types/types/pandas/dataframe.py
  sematic/types/types/pandas/tests/BUILD
  sematic/types/types/pandas/tests/test_dataframe.py
Labels: bug

#67 Documentation for Cloud execution
  README.md
  docs/README.md
  docs/changelog.md
  docs/deploy.md
  docs/execution-modes.md
  sematic/BUILD
  tools/rules.tar
Labels: documentation

#55 Initial setup of titanic survival prediction example
  sematic/examples/titanic_survival_prediction/AUTHORS
  sematic/examples/titanic_survival_prediction/BUILD
  sematic/examples/titanic_survival_prediction/README
  sematic/examples/titanic_survival_prediction/__init__.py
  sematic/examples/titanic_survival_prediction/__main__.py
  sematic/examples/titanic_survival_prediction/consts.py
  sematic/examples/titanic_survival_prediction/data_classes.py
  sematic/examples/titanic_survival_prediction/data_preprocessing.py
  sematic/examples/titanic_survival_prediction/model.py
  sematic/examples/titanic_survival_prediction/pipeline.py
  sematic/examples/titanic_survival_prediction/plots.py
  sematic/examples/titanic_survival_prediction/requirements.txt
  sematic/examples/titanic_survival_prediction/test.py
  sematic/examples/titanic_survival_prediction/train.py
Labels: examples

#71 Persist stack traces and display in UI
  .bazelrc
  README.md
  sematic/db/migrations/20220726001230_add_exception_to_runs_table.sql
  sematic/db/models/run.py
  sematic/db/schema.sql.sqlite
  sematic/examples/bazel/pipeline.py
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/state_machine_resolver.py
  sematic/resolvers/tests/BUILD
  sematic/resolvers/tests/test_local_resolver.py
  sematic/resolvers/tests/test_worker.py
  sematic/resolvers/worker.py
  sematic/ui/src/Models.tsx
  sematic/ui/src/components/DagTab.tsx
Labels: enhancement, ui
