Repository sematic-ai/sematic, pull requests merged in 2022-10, with the labels that each got.

#168 Add link between deploy docs and container docs
  docs/SUMMARY.md
  docs/container-images.md
  docs/deploy.md
  docs/execution-modes.md
Labels: documentation

#167 Add front-end for logging
  docs/changelog.md
  helm/sematic/Chart.yaml
  helm/sematic/templates/sematic-configmap.yaml
  helm/sematic/values.yaml
  sematic/log_reader.py
  sematic/resolvers/worker.py
  sematic/tests/test_log_reader.py
  sematic/ui/README.md
  sematic/ui/package-lock.json
  sematic/ui/package.json
  sematic/ui/src/Payloads.tsx
  sematic/ui/src/addons/grafana/GrafanaPanel.tsx
  sematic/ui/src/components/LogPanel.tsx
  sematic/ui/src/components/RunTabs.tsx
  sematic/ui/src/components/ScrollingLogView.tsx
  sematic/ui/src/index.css
Labels: enhancement, ui

#170 Add Intellij IDEA files to .gitignore
  .gitignore
Labels: housekeeping

#173 Reduce log ingestion test flake
  sematic/resolvers/tests/test_log_streamer.py
Labels: bug

#171 Update documentation with missing links and info
  docs/SUMMARY.md
  docs/architecture.md
  docs/cli.md
  docs/code-style.md
  docs/container-images.md
  docs/contribute-example.md
  docs/contributor-guide.md
  docs/execution-modes.md
  docs/functions.md
  docs/glossary.md
  docs/monorepo.md
  docs/sematic-ui.md
  docs/sematic-vs.md
  docs/snowflake.md
  docs/stack.md
  docs/tooling.md
Labels: documentation

#180 Better logs designs
  sematic/ui/src/components/ScrollingLogView.tsx
  sematic/ui/src/index.css
Labels: ui

#159 Function Retry
  Makefile
  bazel/pipeline.bzl
  docker/Dockerfile.server
  docs/developers/manual.md
  sematic/BUILD
  sematic/__init__.py
  sematic/abstract_future.py
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_runs.py
  sematic/calculator.py
  sematic/cli/cli.py
  sematic/db/BUILD
  sematic/db/migrate.py
  sematic/db/migrations/20220921212247_add_exception_json_field.sql
  sematic/db/migrations/20220930014400_migrate_exception_data.py
  sematic/db/migrations/20221004183943_remove_exception_from_runs.sql
  sematic/db/models/BUILD
  sematic/db/models/run.py
  sematic/db/schema.sql.pg
  sematic/db/schema.sql.sqlite
  sematic/db/tests/BUILD
  sematic/db/tests/test_migrate.py
  sematic/examples/retry/BUILD
  sematic/examples/retry/__init__.py
  sematic/examples/retry/__main__.py
  sematic/examples/retry/pipeline.py
  sematic/resolvers/BUILD
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/state_machine_resolver.py
  sematic/resolvers/tests/BUILD
  sematic/resolvers/tests/test_local_resolver.py
  sematic/resolvers/tests/test_silent_resolver.py
  sematic/resolvers/tests/test_worker.py
  sematic/retry_settings.py
  sematic/scheduling/job_scheduler.py
  sematic/scheduling/kubernetes.py
  sematic/scheduling/tests/test_kubernetes.py
  sematic/tests/BUILD
  sematic/tests/test_retry_settings.py
  sematic/ui/src/Models.tsx
  sematic/ui/src/components/Exception.tsx
  sematic/ui/src/components/LogPanel.tsx
  sematic/ui/src/components/RunNode.tsx
  sematic/ui/src/components/RunStateChip.tsx
  sematic/utils/exceptions.py
Labels: enhancement

#202 Update contributing docs with dev env setup instructions.
  Makefile
  developer-docs/README.md
  docs/contribute-example.md
  docs/developers/guidelines.md
Labels: documentation

#195 Expose pipeline git commit info in the UI
  docs/changelog.md
  requirements/requirements.in
  requirements/requirements.txt
  sematic/db/migrations/20221010210422_add_git_info_to_resolutions.sql
  sematic/db/models/BUILD
  sematic/db/models/json_encodable_mixin.py
  sematic/db/models/resolution.py
  sematic/db/models/tests/BUILD
  sematic/db/models/tests/test_resolution.py
  sematic/db/schema.sql.sqlite
  sematic/db/tests/fixtures.py
  sematic/db/tests/test_queries.py
  sematic/resolvers/BUILD
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
  sematic/scheduling/tests/test_job_scheduler.py
  sematic/ui/src/Models.tsx
  sematic/ui/src/Payloads.tsx
  sematic/ui/src/components/GitInfo.tsx
  sematic/ui/src/components/PipelineBar.tsx
  sematic/ui/src/pipelines/PipelineView.tsx
  sematic/utils/BUILD
  sematic/utils/git.py
Labels: enhancement, wip, ui

#197 Cancel resolution
  docs/cli.md
  requirements/requirements.in
  requirements/requirements.txt
  sematic/abstract_future.py
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/resolutions.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/api_client.py
  sematic/cli/BUILD
  sematic/cli/cancel.py
  sematic/cli/main.py
  sematic/cli/tests/BUILD
  sematic/cli/tests/test_cancel.py
  sematic/cli/tests/test_new.py
  sematic/db/models/resolution.py
  sematic/db/queries.py
  sematic/db/schema.sql.sqlite
  sematic/db/tests/test_queries.py
  sematic/examples/add/pipeline.py
  sematic/examples/mnist/pytorch/mnist_pytorch.py
  sematic/resolvers/BUILD
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/state_machine_resolver.py
  sematic/resolvers/tests/test_cloud_resolver.py
  sematic/resolvers/tests/test_local_resolver.py
  sematic/resolvers/tests/test_worker.py
  sematic/scheduling/kubernetes.py
  sematic/scheduling/tests/test_job_scheduler.py
  sematic/scheduling/tests/test_kubernetes.py
  sematic/ui/src/components/GitInfo.tsx
  sematic/ui/src/components/PipelineBar.tsx
  sematic/ui/src/components/RunStateChip.tsx
  tools/sematic_rules.bzl
Labels: enhancement, ui, cli

#206 Make the MNIST examples runnable in the cloud
  sematic/examples/mnist/pytorch/BUILD
  sematic/examples/mnist/pytorch/mnist_learning_rates.py
  sematic/examples/mnist/pytorch/mnist_train.py
  sematic/examples/mnist/pytorch/pipeline.py
Labels: bug, examples

#205 Fix GitInfo generation when git executable not installed
  sematic/db/models/BUILD
  sematic/db/models/git_info.py
  sematic/db/models/resolution.py
  sematic/db/models/tests/test_resolution.py
  sematic/db/tests/fixtures.py
  sematic/scheduling/tests/test_job_scheduler.py
  sematic/utils/BUILD
  sematic/utils/git.py
  sematic/utils/tests/BUILD
  sematic/utils/tests/test_git.py
Labels: bug

#225 Bump minimum client version to 0.17.0
  sematic/versions.py
Labels: bug, housekeeping

#226 Fix GitInfo for custom Bazel workspaces
  sematic/utils/git.py
Labels: bug

#229 Correct fix GitInfo for custom Bazel workspaces
  sematic/utils/git.py
Labels: bug

#231 Retry exceptions when their ancestors are supposed to be caught
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/db/models/run.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/tests/test_local_resolver.py
  sematic/retry_settings.py
  sematic/tests/test_retry_settings.py
  sematic/utils/exceptions.py
  sematic/utils/tests/BUILD
  sematic/utils/tests/test_exceptions.py
Labels: enhancement

#215 Update the release procedure developer docs
  README.md
  README.rst
  developer-docs/README.md
  requirements/ci-requirements.txt
Labels: documentation, housekeeping

#222 Capability to limit the parallelism degree of CloudResolver
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/silent_resolver.py
  sematic/resolvers/state_machine_resolver.py
  sematic/resolvers/tests/test_cloud_resolver.py
Labels: enhancement

#236 At least one list element
  sematic/types/types/list.py
  sematic/types/types/tests/test_list.py
Labels: enhancement, ui

#241 Fix migrations to not depend on SQLAlchemy models
  docs/changelog.md
  sematic/db/BUILD
  sematic/db/migrations/20220930014400_migrate_exception_data.py
  sematic/db/migrations/20221019225916_migrate_container_image_uris.py
Labels: bug

#246 Multiple base image documentation
  docs/multiple-base-images.md
Labels: documentation

#248 Update deploy.md to mention upgrading bazel
  docs/deploy.md
Labels: documentation

#257 Doc update with resolution testing instructions
  developer-docs/README.md
Labels: documentation

#258 Fix max_parallelism for deached mode
  sematic/api/endpoints/resolutions.py
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/api_client.py
  sematic/examples/bazel/BUILD
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/tests/test_cloud_resolver.py
  sematic/resolvers/worker.py
  sematic/scheduling/job_scheduler.py
  sematic/scheduling/kubernetes.py
  sematic/scheduling/tests/test_job_scheduler.py
Labels: bug, cli

#245 Rerun-from-here base mechanism for local execution
  sematic/BUILD
  sematic/__init__.py
  sematic/abstract_calculator.py
  sematic/abstract_future.py
  sematic/api/endpoints/resolutions.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_auth.py
  sematic/api/endpoints/tests/test_meta.py
  sematic/api/endpoints/tests/test_notes.py
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/api/tests/fixtures.py
  sematic/api_client.py
  sematic/db/models/BUILD
  sematic/db/models/edge.py
  sematic/db/models/factories.py
  sematic/db/models/run.py
  sematic/db/models/tests/BUILD
  sematic/db/models/tests/test_factories.py
  sematic/db/tests/BUILD
  sematic/db/tests/fixtures.py
  sematic/db/tests/test_queries.py
  sematic/examples/add/__main__.py
  sematic/examples/add/pipeline.py
  sematic/graph.py
  sematic/log_reader.py
  sematic/resolvers/BUILD
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/log_streamer.py
  sematic/resolvers/state_machine_resolver.py
  sematic/resolvers/tests/BUILD
  sematic/resolvers/tests/fixtures.py
  sematic/resolvers/tests/test_cloud_resolver.py
  sematic/resolvers/tests/test_local_resolver.py
  sematic/resolvers/tests/test_worker.py
  sematic/resolvers/worker.py
  sematic/scheduling/job_scheduler.py
  sematic/scheduling/kubernetes.py
  sematic/scheduling/tests/test_job_scheduler.py
  sematic/storage.py
  sematic/tests/BUILD
  sematic/tests/fixtures.py
  sematic/tests/test_api_client.py
  sematic/tests/test_graph.py
  sematic/tests/test_log_reader.py
  sematic/ui/src/components/ReactFlowDag.tsx
  sematic/ui/src/components/RunPanel.tsx
  sematic/utils/BUILD
  sematic/utils/memoized_property.py
  sematic/utils/sorting.py
  sematic/utils/tests/BUILD
  sematic/utils/tests/test_sorting.py
Labels: enhancement

#269 Expose Kubernetes infra failures in the Run panel
  docs/changelog.md
  requirements/requirements.in
  sematic/BUILD
  sematic/__init__.py
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/api_client.py
  sematic/db/migrations/20221025201847_add_external_exception_json_field.sql
  sematic/db/migrations/20221027233641_rename_exception_fields_to_metadata.sql
  sematic/db/models/run.py
  sematic/db/schema.sql.sqlite
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/silent_resolver.py
  sematic/resolvers/state_machine_resolver.py
  sematic/resolvers/tests/BUILD
  sematic/resolvers/tests/test_local_resolver.py
  sematic/resolvers/tests/test_silent_resolver.py
  sematic/resolvers/tests/test_worker.py
  sematic/resolvers/worker.py
  sematic/retry_settings.py
  sematic/scheduling/BUILD
  sematic/scheduling/external_job.py
  sematic/scheduling/job_scheduler.py
  sematic/scheduling/kubernetes.py
  sematic/scheduling/tests/test_kubernetes.py
  sematic/testing/tests/BUILD
  sematic/testing/tests/test_mock_funcs.py
  sematic/tests/BUILD
  sematic/tests/test_calculator.py
  sematic/tests/test_retry_settings.py
  sematic/ui/src/Models.tsx
  sematic/ui/src/components/Exception.tsx
  sematic/ui/src/components/LogPanel.tsx
  sematic/utils/exceptions.py
  sematic/versions.py
Labels: enhancement, ui, observability

#265 Support for cloud re-runs and trigger from the UI
  sematic/abstract_future.py
  sematic/api/BUILD
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/events.py
  sematic/api/endpoints/resolutions.py
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/api/server.py
  sematic/db/models/BUILD
  sematic/db/models/factories.py
  sematic/db/models/run.py
  sematic/db/models/tests/BUILD
  sematic/db/models/tests/test_factories.py
  sematic/db/tests/fixtures.py
  sematic/examples/liver_cirrhosis/plots.py
  sematic/graph.py
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/state_machine_resolver.py
  sematic/resolvers/worker.py
  sematic/ui/package-lock.json
  sematic/ui/src/Models.tsx
  sematic/ui/src/Payloads.tsx
  sematic/ui/src/components/ActionMenu.tsx
  sematic/ui/src/components/Artifacts.tsx
  sematic/ui/src/components/CopyButton.tsx
  sematic/ui/src/components/GitInfo.tsx
  sematic/ui/src/components/Notes.tsx
  sematic/ui/src/components/NotesPanel.tsx
  sematic/ui/src/components/PipelineBar.tsx
  sematic/ui/src/components/PipelinePanels.tsx
  sematic/ui/src/components/RunNode.tsx
  sematic/ui/src/components/RunPanel.tsx
  sematic/ui/src/components/RunTabs.tsx
  sematic/ui/src/components/RunTime.tsx
  sematic/ui/src/components/SnackBarProvider.tsx
  sematic/ui/src/index.tsx
  sematic/ui/src/pipelines/PipelineIndex.tsx
  sematic/ui/src/pipelines/PipelineView.tsx
  sematic/ui/src/utils.tsx
Labels: enhancement, ui
