Repository sematic-ai/sematic, pull requests merged in 2023-05, with the labels that each got.

#783 Storybook for the new Run Search page
  sematic/ui/packages/common/src/component/Section.tsx
  sematic/ui/packages/common/src/component/TagsList.tsx
  sematic/ui/packages/common/src/layout/ThreeColumns.tsx
  sematic/ui/packages/common/src/layout/TwoColumns.tsx
  sematic/ui/packages/common/src/muitypes.d.ts
  sematic/ui/packages/common/src/pages/RunSearch/SearchFilters.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/CollapseableFilterSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/OrderSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/OtherFilterSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/OwnersFilterSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/SearchTextSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/StatusFilterSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/TagsFilterSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/common.ts
  sematic/ui/packages/common/src/pages/RunSearch/index.tsx
  sematic/ui/packages/common/src/theme/new/componnets.ts
  sematic/ui/packages/common/src/theme/new/palette.ts
  sematic/ui/packages/storybook/src/stories/Color.stories.tsx
  sematic/ui/packages/storybook/src/stories/Page.stories.tsx
  sematic/ui/packages/storybook/src/stories/RunFilter.stories.tsx
Labels: ui

#789 Update command for wheel build
  docs/developers/manual.md
Labels: documentation, build

#681 Reduce socket calls in high-fan out pipelines
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/test_runs.py
Labels: scaling

#788 Update the dev manual
  docs/developers/manual.md
Labels: documentation, build

#791 Fix cleaning of runs in the CREATED state
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/test_runs.py
Labels: bug

#787 A component to allow creating tag filters dynamically
  sematic/ui/packages/common/src/component/TagsInput.tsx
  sematic/ui/packages/common/src/pages/RunSearch/SearchFilters.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/CollapseableFilterSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/OwnersFilterSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/StatusFilterSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/TagsFilterSection.tsx
  sematic/ui/packages/common/src/theme/new/componnets.ts
  sematic/ui/packages/storybook/src/stories/Tags.stories.tsx
Labels: ui

#796 Release 0.29.0
  README.md
  README.rst
  docs/changelog.md
  helm/sematic-server/Chart.yaml
  sematic/api/endpoints/runs.py
  sematic/ui/packages/main/src/types/image.tsx
  sematic/versions.py
  sematic/wheel_constants.bzl
Labels: release

#794 Support setting the feature flag for new dashboard
  sematic/ui/package-lock.json
  sematic/ui/packages/common/src/utils/FeatureFlagManager.ts
  sematic/ui/packages/common/src/utils/logging.ts
  sematic/ui/packages/main/package.json
  sematic/ui/packages/main/src/components/tests/tеst_normal.tsx
  sematic/ui/packages/main/src/index.tsx
Labels: enhancement, ui

#798 List users endpoint
  sematic/api/BUILD
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/payloads.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_users.py
  sematic/api/endpoints/users.py
  sematic/api/server.py
  sematic/db/queries.py
Labels: housekeeping

#777 [1/N] Native Build System for custom images
  requirements/requirements.in
  requirements/requirements3_10.txt
  requirements/requirements3_8.txt
  requirements/requirements3_9.txt
  sematic/abstract_plugin.py
  sematic/plugins/BUILD
  sematic/plugins/abstract_builder.py
  sematic/plugins/building/BUILD
  sematic/plugins/building/__init__.py
  sematic/plugins/building/docker_builder.py
Labels: enhancement, build

#790 [2/N] Native Build System starting from base images
  sematic/plugins/abstract_builder.py
  sematic/plugins/building/docker_builder.py
Labels: enhancement, build

#800 Fixes a DAG view display issue
  sematic/ui/packages/main/src/pipelines/graph/RunNode.tsx
Labels: bug, ui

#806 [6/N] User metrics SDK
  sematic/BUILD
  sematic/api_client.py
  sematic/ee/BUILD
  sematic/ee/metrics.py
  sematic/ee/tests/BUILD
  sematic/ee/tests/test_metrics.py
  sematic/tests/BUILD
  sematic/tests/__init__.py
  sematic/tests/test_api_client.py
Labels: metrics

#812 Fix calculator_path client backwards compatibility
  sematic/api/endpoints/payloads.py
  sematic/api/endpoints/tests/test_runs.py
Labels: bug

#807 [3/N] Docker Build System unit tests
  sematic/plugins/BUILD
  sematic/plugins/building/docker_builder.py
  sematic/plugins/building/tests/BUILD
  sematic/plugins/building/tests/__init__.py
  sematic/plugins/building/tests/fixtures/bad_image_script.sh
  sematic/plugins/building/tests/fixtures/bad_launch_script.py
  sematic/plugins/building/tests/fixtures/bad_version.yaml
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.basic
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.data
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.full
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.requirements
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.src
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.target
  sematic/plugins/building/tests/fixtures/good_image_script.sh
  sematic/plugins/building/tests/fixtures/good_launch_script.py
  sematic/plugins/building/tests/fixtures/good_launch_script.yaml
  sematic/plugins/building/tests/fixtures/good_minimal.yaml
  sematic/plugins/building/tests/fixtures/malformed_push1.yaml
  sematic/plugins/building/tests/fixtures/malformed_push2.yaml
  sematic/plugins/building/tests/fixtures/malformed_uri.yaml
  sematic/plugins/building/tests/fixtures/no_image.yaml
  sematic/plugins/building/tests/fixtures/two_images.yaml
  sematic/plugins/building/tests/test_docker_builder.py
Labels: testing, build

#813 [4/N] Build System configurable Docker connection
  sematic/plugins/building/docker_builder.py
  sematic/plugins/building/tests/fixtures/good_launch_script.yaml
  sematic/plugins/building/tests/test_docker_builder.py
Labels: usability, build

#810 Search table static page
  sematic/ui/package-lock.json
  sematic/ui/package.json
  sematic/ui/packages/common/package.json
  sematic/ui/packages/common/src/component/DateTime.tsx
  sematic/ui/packages/common/src/component/RunReferenceLink.tsx
  sematic/ui/packages/common/src/component/RunStateChips.tsx
  sematic/ui/packages/common/src/component/RunStateText.ts
  sematic/ui/packages/common/src/component/Table.tsx
  sematic/ui/packages/common/src/component/TagsList.tsx
  sematic/ui/packages/common/src/layout/TwoColumns.tsx
  sematic/ui/packages/common/src/muitypes.d.ts
  sematic/ui/packages/common/src/pages/RunDetails/FunctionSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/RunList.tsx
  sematic/ui/packages/common/src/pages/RunSearch/RunStatusColumn.tsx
  sematic/ui/packages/common/src/pages/RunSearch/SearchFilters.tsx
  sematic/ui/packages/common/src/pages/RunSearch/index.tsx
  sematic/ui/packages/common/src/theme/new/components.ts
  sematic/ui/packages/common/src/theme/new/index.ts
  sematic/ui/packages/storybook/src/stories/RunStateChip.stories.tsx
Labels: ui

#814 Fix log duplication
  sematic/logging.py
Labels: bug, usability

#811 Add horizontal pod autoscaling and pod disruption budget for API server
  helm/sematic-server/templates/hpa.yaml
  helm/sematic-server/templates/pdb.yaml
  helm/sematic-server/values.yaml
Labels: scaling, infrastructure

#799 Add health endpoint that detects DB access failure, display status in UI
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/meta.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_meta.py
  sematic/ui/packages/main/src/components/Health.tsx
  sematic/ui/packages/main/src/components/SnackBarProvider.tsx
  sematic/ui/packages/main/src/index.tsx
  sematic/ui/packages/main/src/pipelines/PipelineBar.tsx
Labels: db, infrastructure, reliability

#808 #536 : Feature/add set type support
  docs/developers/manual.md
  sematic/types/BUILD
  sematic/types/__init__.py
  sematic/types/registry.py
  sematic/types/tests/test_casting.py
  sematic/types/tests/test_registry.py
  sematic/types/types/BUILD
  sematic/types/types/set.py
Labels: enhancement, types

#815 [5/N] Run pipeline build through CLI
  sematic/api_client.py
  sematic/cli/BUILD
  sematic/cli/run.py
  sematic/logging.py
  sematic/plugins/building/docker_builder.py
  sematic/plugins/building/tests/fixtures/bad_version.yaml
  sematic/plugins/building/tests/fixtures/good_launch_script.yaml
  sematic/plugins/building/tests/fixtures/good_minimal.yaml
  sematic/plugins/building/tests/fixtures/malformed_push1.yaml
  sematic/plugins/building/tests/fixtures/malformed_push2.yaml
  sematic/plugins/building/tests/fixtures/malformed_uri.yaml
  sematic/plugins/building/tests/fixtures/no_image.yaml
  sematic/plugins/building/tests/fixtures/two_images.yaml
  sematic/tests/test_api_client.py
Labels: enhancement, cli, build

#817 [6/N] Extract and reuse utility functions in DockerBuiler
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_auth.py
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/config/BUILD
  sematic/config/server_settings.py
  sematic/config/settings.py
  sematic/config/tests/BUILD
  sematic/config/tests/test_config_dir.py
  sematic/config/tests/test_settings.py
  sematic/config/user_settings.py
  sematic/ee/plugins/external_resource/ray/tests/BUILD
  sematic/ee/plugins/external_resource/ray/tests/test_cluster.py
  sematic/plugins/building/BUILD
  sematic/plugins/building/docker_builder.py
  sematic/plugins/kuberay_wrapper/tests/BUILD
  sematic/plugins/kuberay_wrapper/tests/test_standard.py
  sematic/plugins/publishing/tests/BUILD
  sematic/plugins/publishing/tests/test_slack.py
  sematic/resolvers/tests/BUILD
  sematic/resolvers/tests/test_cloud_resolver.py
  sematic/resolvers/tests/test_worker.py
  sematic/scheduling/tests/BUILD
  sematic/scheduling/tests/test_kubernetes.py
  sematic/tests/fixtures.py
  sematic/utils/BUILD
  sematic/utils/env.py
  sematic/utils/types.py
Labels: tech debt, build

#816 Use real run data in search table
  sematic/ui/packages/common/src/ApiContracts.ts
  sematic/ui/packages/common/src/component/DateTime.tsx
  sematic/ui/packages/common/src/component/Loading.tsx
  sematic/ui/packages/common/src/component/Note.tsx
  sematic/ui/packages/common/src/component/RunReference.tsx
  sematic/ui/packages/common/src/component/RunReferenceLink.tsx
  sematic/ui/packages/common/src/component/RunStateChips.tsx
  sematic/ui/packages/common/src/component/RunStateText.ts
  sematic/ui/packages/common/src/component/Table.tsx
  sematic/ui/packages/common/src/component/TagsList.tsx
  sematic/ui/packages/common/src/context/LayoutServiceContext.ts
  sematic/ui/packages/common/src/hooks/runHooks.ts
  sematic/ui/packages/common/src/layout/Shell.tsx
  sematic/ui/packages/common/src/layout/TwoColumns.tsx
  sematic/ui/packages/common/src/pages/RunDetails/FunctionSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/RunList.tsx
  sematic/ui/packages/common/src/pages/RunSearch/RunStatusColumn.tsx
  sematic/ui/packages/common/src/pages/RunSearch/TagsColumn.tsx
  sematic/ui/packages/common/src/reactHooks.ts
  sematic/ui/packages/main/src/Home.tsx
  sematic/ui/packages/main/src/Payloads.tsx
  sematic/ui/packages/main/src/components/BidirectionalLogView.tsx
  sematic/ui/packages/main/src/components/RunId.tsx
  sematic/ui/packages/main/src/components/RunList.tsx
  sematic/ui/packages/main/src/hooks/pipelineHooks.ts
  sematic/ui/packages/main/src/hooks/podHistoryHooks.ts
  sematic/ui/packages/main/src/index.tsx
  sematic/ui/packages/main/src/pipelines/PipelineBar.tsx
  sematic/ui/packages/main/src/pipelines/PipelineIndex.tsx
  sematic/ui/packages/main/src/pipelines/PipelineView.tsx
  sematic/ui/packages/main/src/pipelines/pod_lifecycle/PodEventHistory.tsx
  sematic/ui/packages/main/src/pipelines/pod_lifecycle/PodLifecycle.tsx
  sematic/ui/packages/main/src/pipelines/pod_lifecycle/PodLifecycleEvent.tsx
  sematic/ui/packages/main/src/runs/RunIndex.tsx
  sematic/ui/packages/storybook/src/stories/Notes.stories.tsx
  sematic/ui/packages/storybook/src/stories/Page.stories.tsx
Labels: ui

#801 Have resolver continue in a new resolution if resolver restarts
  sematic/__init__.py
  sematic/abstract_future.py
  sematic/api/endpoints/resolutions.py
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/api_client.py
  sematic/graph.py
  sematic/resolvers/BUILD
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/resource_requirements.py
  sematic/resolvers/tests/test_cloud_resolver.py
  sematic/resolvers/worker.py
  sematic/scheduling/BUILD
  sematic/scheduling/job_scheduler.py
  sematic/scheduling/kubernetes.py
  sematic/scheduling/tests/test_job_scheduler.py
Labels: enhancement, reliability

#821 Add some mechanisms to make DB connection handling more robust
  sematic/db/db.py
Labels: scaling, reliability

#825 [New dashboard UI] Apply or reset search filters
  sematic/ui/packages/common/src/ApiContracts.ts
  sematic/ui/packages/common/src/component/TagsInput.tsx
  sematic/ui/packages/common/src/component/common.ts
  sematic/ui/packages/common/src/hooks/userHooks.ts
  sematic/ui/packages/common/src/pages/RunSearch/RunList.tsx
  sematic/ui/packages/common/src/pages/RunSearch/SearchFilters.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/OtherFilterSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/OwnersFilterSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/SearchTextSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/StatusFilterSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/TagsFilterSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/common.ts
  sematic/ui/packages/common/src/pages/RunSearch/index.tsx
  sematic/ui/packages/storybook/src/stories/RunFilter.stories.tsx
Labels: enhancement, ui

#831 Add support for searching by tags
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/request_parameters.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/db/models/mixins/json_encodable_mixin.py
  sematic/db/models/run.py
Labels: enhancement

#834 Switch to apt-get
  docker/Dockerfile.ci
  docker/Dockerfile.worker
  sematic/plugins/building/docker_builder.py
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.basic
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.data
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.full
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.requirements
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.src
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.target
Labels: usability, build

#836 Display empty state in run search table
  sematic/ui/packages/common/src/component/NameTag.tsx
  sematic/ui/packages/common/src/component/Note.tsx
  sematic/ui/packages/common/src/component/ShellCommand.tsx
  sematic/ui/packages/common/src/hooks/runHooks.ts
  sematic/ui/packages/common/src/pages/RunSearch/RunList.tsx
  sematic/ui/packages/common/src/pages/RunSearch/RunListEmptyState.tsx
  sematic/ui/packages/common/src/pages/RunSearch/SearchFilters.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/OwnersFilterSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/index.tsx
  sematic/ui/packages/main/src/Home.tsx
  sematic/ui/packages/main/src/components/TrackingNotice.tsx
Labels: ui

#843 Wrap Docker update messages
  sematic/plugins/building/BUILD
  sematic/plugins/building/docker_builder.py
  sematic/plugins/building/docker_client_utils.py
  sematic/plugins/building/tests/BUILD
  sematic/plugins/building/tests/test_docker_builder.py
  sematic/plugins/building/tests/test_docker_client_utils.py
Labels: bug, usability, build

#844 Add build config files for example pipelines
  sematic/cli/tests/test_new.py
  sematic/examples/mnist/pytorch/__main__.yaml
  sematic/examples/mnist/pytorch/mnist_learning_rates.yaml
  sematic/examples/mnist/pytorch/mnist_train.yaml
  sematic/examples/mnist/pytorch/requirements.txt
  sematic/examples/template/__main__.yaml
  sematic/examples/template/requirements.txt
Labels: examples, build

#845 Enable run search deep link
  sematic/ee/plugins/publishing/github/check.py
  sematic/ui/packages/main/src/runs/RunIndex.tsx
Labels: enhancement, ui

#840 Use real data for pipeline and run section
  sematic/ui/packages/common/src/ApiContracts.ts
  sematic/ui/packages/common/src/component/DateTime.tsx
  sematic/ui/packages/common/src/component/RunsDropdown.tsx
  sematic/ui/packages/common/src/component/TimeAgo.tsx
  sematic/ui/packages/common/src/component/tests/test_RunsDropdown.cy.tsx
  sematic/ui/packages/common/src/context/RootRunContext.ts
  sematic/ui/packages/common/src/hooks/metricsHooks.ts
  sematic/ui/packages/common/src/hooks/resolutionHooks.ts
  sematic/ui/packages/common/src/hooks/runHooks.ts
  sematic/ui/packages/common/src/pages/RunDetails/PipelineSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunRouter.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/index.tsx
  sematic/ui/packages/common/src/utils/datetime.ts
  sematic/ui/packages/common/src/utils/typings.ts
  sematic/ui/packages/common/src/utils/url.ts
  sematic/ui/packages/main/src/Payloads.tsx
  sematic/ui/packages/main/src/components/Notes.tsx
  sematic/ui/packages/main/src/components/RunTime.tsx
  sematic/ui/packages/main/src/hooks/metricsHooks.ts
  sematic/ui/packages/main/src/hooks/pipelineHooks.ts
  sematic/ui/packages/main/src/pipelines/BasicMetricsPanel.tsx
  sematic/ui/packages/main/src/pipelines/PipelineBar.tsx
  sematic/ui/packages/main/src/pipelines/PipelineIndex.tsx
  sematic/ui/packages/main/src/pipelines/PipelinePanels.tsx
  sematic/ui/packages/main/src/pipelines/PipelineRunView.tsx
  sematic/ui/packages/main/src/pipelines/PipelineView.tsx
  sematic/ui/packages/main/src/runs/RunIndex.tsx
  sematic/ui/packages/main/src/utils.tsx
  sematic/ui/packages/storybook/src/stories/Dropdown.stories.tsx
  sematic/ui/packages/storybook/src/stories/Page.stories.tsx
  sematic/ui/packages/tests/cypress.config.ts
  sematic/ui/packages/tests/cypress_screenshots/common/src/component/tests/RunsDropdown component -- should render #0.png
Labels: ui

#848 Use real data for new run details page part 2
  sematic/ui/packages/common/src/ApiContracts.ts
  sematic/ui/packages/common/src/component/GitInfo.tsx
  sematic/ui/packages/common/src/component/RunStateText.ts
  sematic/ui/packages/common/src/component/RunTree.tsx
  sematic/ui/packages/common/src/component/RunsDropdown.tsx
  sematic/ui/packages/common/src/component/TagsList.tsx
  sematic/ui/packages/common/src/constants.ts
  sematic/ui/packages/common/src/context/RootRunContext.ts
  sematic/ui/packages/common/src/context/RunDetailsSelectionContext.ts
  sematic/ui/packages/common/src/context/SnackBarContext.ts
  sematic/ui/packages/common/src/context/SnackBarProvider.tsx
  sematic/ui/packages/common/src/context/graphContext.ts
  sematic/ui/packages/common/src/hooks/graphHooks.ts
  sematic/ui/packages/common/src/hooks/hashHooks.ts
  sematic/ui/packages/common/src/hooks/tests/test_graphHooks.cy.tsx
  sematic/ui/packages/common/src/interfaces/graph.ts
  sematic/ui/packages/common/src/pages/RunDetails/FunctionSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/GitSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunTreeSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/index.tsx
  sematic/ui/packages/common/src/sockets.ts
  sematic/ui/packages/common/src/utils/datetime.ts
  sematic/ui/packages/common/src/utils/url.ts
  sematic/ui/packages/main/src/components/GitInfo.tsx
  sematic/ui/packages/main/src/hooks/pipelineHooks.ts
  sematic/ui/packages/main/src/pipelines/MenuPanel.tsx
  sematic/ui/packages/main/src/pipelines/PipelinePanels.tsx
  sematic/ui/packages/main/src/pipelines/RunDetailsPanel.tsx
  sematic/ui/packages/main/src/pipelines/RunPanel.tsx
  sematic/ui/packages/main/src/pipelines/RunTree.tsx
  sematic/ui/packages/main/src/pipelines/graph/ReactFlowDag.tsx
  sematic/ui/packages/main/src/sockets.ts
  sematic/ui/packages/storybook/src/stories/GitInfo.stories.tsx
  sematic/ui/packages/storybook/src/stories/RunFilter.stories.tsx
  sematic/ui/packages/storybook/src/stories/SideBar.stories.tsx
  sematic/ui/packages/storybook/src/stories/Tree.stories.tsx
Labels: ui, housekeeping

#850 [7/N] Relative build config paths and config file merging
  sematic/examples/mnist/pytorch/__main__.yaml
  sematic/examples/mnist/pytorch/mnist_learning_rates.yaml
  sematic/examples/mnist/pytorch/mnist_train.yaml
  sematic/plugins/building/BUILD
  sematic/plugins/building/docker_builder.py
  sematic/plugins/building/docker_builder_config.py
  sematic/plugins/building/tests/BUILD
  sematic/plugins/building/tests/fixtures/absolute_data.yaml
  sematic/plugins/building/tests/fixtures/absolute_image_script.yaml
  sematic/plugins/building/tests/fixtures/absolute_requirements.yaml
  sematic/plugins/building/tests/fixtures/absolute_src.yaml
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.full
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.requirements
  sematic/plugins/building/tests/fixtures/good_launch_script.py
  sematic/plugins/building/tests/fixtures/good_launch_script.yaml
  sematic/plugins/building/tests/fixtures/good_minimal.py
  sematic/plugins/building/tests/fixtures/good_minimal.yaml
  sematic/plugins/building/tests/fixtures/jailbreak_data.yaml
  sematic/plugins/building/tests/fixtures/jailbreak_image_script.yaml
  sematic/plugins/building/tests/fixtures/jailbreak_requirements.yaml
  sematic/plugins/building/tests/fixtures/jailbreak_src.yaml
  sematic/plugins/building/tests/fixtures/malformed_push_empty_registry.yaml
  sematic/plugins/building/tests/fixtures/malformed_push_missing_repository.yaml
  sematic/plugins/building/tests/fixtures/nested/ignored.yaml
  sematic/plugins/building/tests/fixtures/nested/launch_script.py
  sematic/plugins/building/tests/fixtures/nested/launch_script.yaml
  sematic/plugins/building/tests/fixtures/nested/launch_script_no_specific_config.py
  sematic/plugins/building/tests/fixtures/nested/sematic_build.yaml
  sematic/plugins/building/tests/fixtures/not_executable
  sematic/plugins/building/tests/fixtures/sematic_build.yaml
  sematic/plugins/building/tests/test_docker_builder.py
  sematic/plugins/building/tests/test_docker_builder_config.py
Labels: enhancement, build

#852 [New dashboard] Render and submit notes in the right pane of run details page
  sematic/ui/packages/common/src/ApiContracts.ts
  sematic/ui/packages/common/src/component/GitInfo.tsx
  sematic/ui/packages/common/src/component/Note.tsx
  sematic/ui/packages/common/src/hooks/noteHooks.ts
  sematic/ui/packages/common/src/layout/ThreeColumns.tsx
  sematic/ui/packages/common/src/pages/RunDetails/NotesPane.tsx
  sematic/ui/packages/main/src/Payloads.tsx
  sematic/ui/packages/main/src/pipelines/NotesPanel.tsx
Labels: ui

#858 Dump the SQL schema to the current schema file by default
  sematic/db/migrate.py
Labels: cli, housekeeping, db, usability

#856 Avoid pip resolution bug
  sematic/plugins/building/docker_builder.py
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.basic
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.data
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.full
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.requirements
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.src
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.target
Labels: bug, build

#861 Disable Docker updates rolling window on DEBUG level
  sematic/plugins/building/BUILD
  sematic/plugins/building/docker_builder.py
  sematic/plugins/building/docker_client_utils.py
  sematic/utils/BUILD
  sematic/utils/spinner.py
Labels: cli, usability, build
