Repository sematic-ai/sematic, pull requests merged in 2023-02, with the labels that each got.

#520 Parallelizing CI run
  .circleci/config.yml
Labels: infrastructure

#528 Bump release version to 0.23.0
  docs/changelog.md
  helm/sematic-server/Chart.yaml
  sematic/versions.py
  sematic/wheel_version.bzl
Labels: release

#523 Introduces cypress test
  .gitignore
  sematic/ui/package-lock.json
  sematic/ui/package.json
  sematic/ui/src/components/RunList.tsx
  sematic/ui/src/pipelines/PipelineIndex.tsx
  sematic/ui/tests/.eslintrc.json
  sematic/ui/tests/cypress.config.ts
  sematic/ui/tests/e2e/main.cy.ts
  sematic/ui/tests/fixtures/example.json
  sematic/ui/tests/global.d.ts
  sematic/ui/tests/support/commands.ts
  sematic/ui/tests/support/e2e.ts
  sematic/ui/tests/tsconfig.json
Labels: ui, ci

#529 Add ts linting to `pre-commit` make command
  Makefile
  docs/developers/guidelines.md
Labels: documentation, housekeeping

#534 Don't specify an image tag by default in Helm chart
  helm/sematic-server/values.yaml
Labels: bug, infrastructure

#535 Make untyped dict error message is clearer, ensure propagation in dataclasses
  sematic/types/types/dataclass.py
  sematic/types/types/dict.py
  sematic/types/types/tests/test_dataclass.py
Labels: usability

#532 "Tee" logs to pod stdout as well as Sematic ingestion
  sematic/resolvers/log_streamer.py
  sematic/resolvers/tests/test_log_streamer.py
  sematic/utils/stdout.py
Labels: enhancement, observability

#525 Make Kuberay wrapper configurable via Helm chart
  helm/sematic-server/templates/configmap.yaml
  helm/sematic-server/values.yaml
  sematic/abstract_plugin.py
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/config/server_settings.py
  sematic/config/settings.py
  sematic/config/tests/BUILD
  sematic/config/tests/test_settings.py
  sematic/config/user_settings.py
  sematic/plugins/BUILD
  sematic/plugins/abstract_external_resource.py
  sematic/plugins/abstract_kuberay_wrapper.py
  sematic/plugins/kuberay_wrapper/standard.py
  sematic/plugins/publishing/slack.py
  sematic/plugins/storage/local_storage.py
  sematic/plugins/storage/memory_storage.py
  sematic/plugins/storage/s3_storage.py
Labels: enhancement, infrastructure

#497 Ray as an external resource
  Makefile
  developer-docs/README.md
  docker/Dockerfile.server
  docs/changelog.md
  docs/deploy.md
  helm/sematic-server/templates/configmap.yaml
  helm/sematic-server/templates/server-role.yaml
  helm/sematic-server/values.yaml
  sematic/BUILD
  sematic/__init__.py
  sematic/abstract_plugin.py
  sematic/api/endpoints/external_resources.py
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/config/server_settings.py
  sematic/config/settings.py
  sematic/config/tests/BUILD
  sematic/config/tests/test_settings.py
  sematic/config/user_settings.py
  sematic/db/queries.py
  sematic/ee/BUILD
  sematic/ee/extras.bzl
  sematic/ee/plugins/external_resource/ray/BUILD
  sematic/ee/plugins/external_resource/ray/cluster.py
  sematic/ee/plugins/external_resource/ray/tests/BUILD
  sematic/ee/plugins/external_resource/ray/tests/test_cluster.py
  sematic/ee/ray.py
  sematic/examples/testing_pipeline/BUILD
  sematic/examples/testing_pipeline/__main__.py
  sematic/examples/testing_pipeline/pipeline.py
  sematic/plugins/BUILD
  sematic/plugins/abstract_external_resource.py
  sematic/plugins/abstract_kuberay_wrapper.py
  sematic/plugins/kuberay_wrapper/standard.py
  sematic/plugins/publishing/slack.py
  sematic/plugins/storage/local_storage.py
  sematic/plugins/storage/memory_storage.py
  sematic/plugins/storage/s3_storage.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/state_machine_resolver.py
  sematic/tests/BUILD
  sematic/tests/test_versions.py
  sematic/wheel_constants.bzl
  sematic/wheel_version.bzl
  tools/sematic_rules.bzl
  tools/sematic_wheel_rule.bzl
Labels: enhancement, scaling, infrastructure

#531 Improve run/resolution cleanup (clearer root cause, resolver restarts)
  sematic/abstract_future.py
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/resolutions.py
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/db/models/resolution.py
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/tests/test_cloud_resolver.py
  sematic/resolvers/tests/test_local_resolver.py
  sematic/scheduling/kubernetes.py
Labels: enhancement, reliability

#538 Function output caching unit tests
  sematic/resolvers/tests/BUILD
  sematic/resolvers/tests/test_local_resolver.py
  sematic/tests/fixtures.py
  sematic/types/types/dict.py
Labels: tech debt, testing

#511 Unified upload endpoints
  sematic/BUILD
  sematic/api/BUILD
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/artifacts.py
  sematic/api/endpoints/auth.py
  sematic/api/endpoints/storage.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_artifacts.py
  sematic/api/endpoints/tests/test_storage.py
  sematic/api/server.py
  sematic/api/tests/fixtures.py
  sematic/api_client.py
  sematic/config/BUILD
  sematic/config/config.py
  sematic/config/tests/BUILD
  sematic/config/tests/test_settings.py
  sematic/db/tests/fixtures.py
  sematic/plugins/BUILD
  sematic/plugins/abstract_storage.py
  sematic/plugins/storage/BUILD
  sematic/plugins/storage/local_storage.py
  sematic/plugins/storage/memory_storage.py
  sematic/plugins/storage/s3_storage.py
  sematic/plugins/storage/tests/test_local_storage.py
  sematic/plugins/storage/tests/test_memory_storage.py
  sematic/plugins/storage/tests/test_s3_storage.py
  sematic/resolvers/tests/test_local_resolver.py
Labels: enhancement, tech debt

#519 Update the documentation with new features
  docs/SUMMARY.md
  docs/advanced-apis.md
  docs/advanced-features.md
  docs/api.md
  docs/architecture.md
  docs/bigquery.md
  docs/cloud-resolver.md
  docs/code-style.md
  docs/dataflow.md
  docs/dbt.md
  docs/execution-modes.md
  docs/functions.md
  docs/future-algebra.md
  docs/glossary.md
  docs/monorepo.md
  docs/multiple-base-images.md
  docs/redshift.md
  docs/sematic-ui.md
  docs/slack.md
  docs/stack.md
  docs/testing.md
  docs/tooling.md
  sematic/future.py
  sematic/future_operators/iter.py
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
  sematic/types/registry.py
Labels: documentation, enhancement, housekeeping

#526 Running Cypres integration test in CircleCI
  .circleci/config.yml
  Makefile
  sematic/tests/integration/test_pip_install.sh
  sematic/ui/tests/cypress.config.ts
  sematic/ui/tests/e2e/main.cy.ts
Labels: ui, tech debt, ci, testing, infrastructure

#543 Avoid urllib usage killing WSGI workers on MacOS
  sematic/__init__.py
Labels: bug

#544 Fix lint on main
  sematic/resolvers/tests/test_local_resolver.py
Labels: bug, ci

#545 Fix client hanging after multiple cancelation events
  sematic/api/endpoints/resolutions.py
  sematic/api/endpoints/tests/test_resolutions.py
Labels: bug

#547 Fix an incorrect name in the Helm chart
  helm/sematic-server/values.yaml
Labels: bug, infrastructure

#549 Warn on Python migration error
  sematic/db/migrate.py
  sematic/db/migrations/20221214142609_plugin_settings_file.py
Labels: cli, tech debt, db, usability

#548 Release Sematic v0.24.0
  developer-docs/README.md
  docs/changelog.md
  helm/sematic-server/Chart.yaml
  helm/sematic-server/values.yaml
  sematic/versions.py
  sematic/wheel_constants.bzl
Labels: release

#551 Simplify the Circleci Slack notification configuration
  .circleci/config.yml
Labels: ci

#553 Release v0.24.1
  docs/SUMMARY.md
  docs/changelog.md
  docs/deploy.md
  docs/upgrades.md
  helm/sematic-server/Chart.yaml
  sematic/versions.py
  sematic/wheel_constants.bzl
Labels: release

#557 Fix Slack publishing Helm activation
  helm/sematic-server/templates/configmap.yaml
Labels: bug, infrastructure

#540 Full-text run search
  .gitignore
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/ui/src/components/RunList.tsx
  sematic/ui/src/components/SideBar.tsx
  sematic/ui/src/hooks/domHooks.ts
  sematic/ui/src/index.tsx
  sematic/ui/src/pipelines/PipelineIndex.tsx
  sematic/ui/src/runs/RunIndex.tsx
  sematic/ui/src/utils.tsx
Labels: enhancement, ui, usability

#556 Add more detailed Ray docs
  docs/SUMMARY.md
  docs/deploy.md
  docs/ray.md
  docs/upgrades.md
Labels: documentation

#558 Refactor pipeline page layout
  sematic/ui/src/pipelines/PipelineIndex.tsx
Labels: ui, housekeeping, usability

#550 Fix Resolver import error on Server plugin
  sematic/config/settings.py
  sematic/config/tests/BUILD
  sematic/config/tests/test_settings.py
Labels: bug

#560 Add notice that Ray is an EE feature
  docs/ray.md
Labels: documentation

#562 Release Helm charts v1.1.2 with Sematic v0.24.1
  helm/sematic-server/Chart.yaml
Labels: release

#564 Update CI lint step to match dev linting
  .circleci/config.yml
  sematic/api/endpoints/runs.py
Labels: tech debt, ci

#569 Use configurable timeouts
  docs/ray.md
  sematic/ee/plugins/external_resource/ray/cluster.py
  sematic/ee/plugins/external_resource/ray/tests/test_cluster.py
  sematic/plugins/abstract_external_resource.py
  sematic/resolvers/state_machine_resolver.py
  sematic/resolvers/tests/fixtures.py
  sematic/resolvers/tests/test_silent_resolver.py
Labels: enhancement, infrastructure

#575 Supports runs link
  sematic/ui/package-lock.json
  sematic/ui/package.json
  sematic/ui/src/components/RunId.tsx
  sematic/ui/src/hooks/pipelineHooks.ts
  sematic/ui/src/index.tsx
  sematic/ui/src/pipelines/OutputPanel.tsx
  sematic/ui/src/pipelines/PipelineBar.tsx
  sematic/ui/src/pipelines/PipelineRunView.tsx
  sematic/ui/src/pipelines/PipelineRunViewContext.ts
  sematic/ui/src/pipelines/PipelineView.tsx
  sematic/ui/src/runs/RunIndex.tsx
Labels: enhancement, ui

#574 Resilient against non-standard torch import fails
  sematic/types/types/pytorch/__init__.py
Labels: bug, reliability

#587 Fix noop SQL migrations
  sematic/db/migrate.py
  sematic/db/tests/test_migrate.py
Labels: bug, db

#586 Reference new support email
  docs/changelog.md
  docs/ray.md
  docs/upgrades.md
  sematic/ee/LICENSE
  sematic/ee/README.md
  sematic/ui/src/Home.tsx
Labels: documentation

#576 Move future pickle storage to new server-generated locations
  sematic/api_client.py
  sematic/resolvers/BUILD
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/worker.py
Labels: tech debt

#590 Integrate PostHog event capturing
  .circleci/config.yml
  sematic/ui/package-lock.json
  sematic/ui/package.json
  sematic/ui/src/Home.tsx
  sematic/ui/src/Payloads.tsx
  sematic/ui/src/components/TrackingNotice.tsx
  sematic/ui/src/index.tsx
  sematic/ui/src/postHogManager.ts
  sematic/ui/src/runs/RunIndex.tsx
  sematic/ui/src/utils.tsx
Labels: enhancement, ui

#589 Atomic database migrations with Helm hooks
  .flake8
  helm/sematic-server/templates/NOTES.txt
  helm/sematic-server/templates/_helpers.tpl
  helm/sematic-server/templates/migration-job.yaml
  helm/sematic-server/values.yaml
  sematic/cli/BUILD
  sematic/cli/cli.py
  sematic/cli/main.py
Labels: tech debt, db, infrastructure

#606 Correct rerun documentation
  docs/api.md
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
Labels: documentation

#607 Remove path info
  sematic/ui/src/index.tsx
Labels: enhancement, ui, observability

#610 Release 0.26.0
  docs/changelog.md
  helm/sematic-server/Chart.yaml
  sematic/versions.py
  sematic/wheel_constants.bzl
Labels: release

#571 Add support for Python3.10
  .circleci/config.yml
  BUILD
  Makefile
  README.md
  README.rst
  WORKSPACE
  developer-docs/tips-for-bazel.md
  docker/Dockerfile.server
  docs/changelog.md
  docs/get-started.md
  docs/upgrades.md
  mypy.ini
  requirements/BUILD
  requirements/requirements.in
  requirements/requirements38.txt
  requirements/requirements3_10.txt
  requirements/requirements3_8.txt
  requirements/requirements3_9.txt
  sematic/api/BUILD
  sematic/api/server.py
  sematic/cli/start.py
  sematic/tests/BUILD
  sematic/tests/test_3_10_interpreter.py
  sematic/tests/test_3_8_interpreter.py
  sematic/tests/test_3_9_interpreter.py
  sematic/wheel_constants.bzl
  tools/build_rules/prelude_bazel
  tools/sematic_rules.bzl
Labels: enhancement, infrastructure

#604 Support python 3.10-style type hints
  sematic/calculator.py
  sematic/tests/BUILD
  sematic/tests/test_3_10_calculator.py
  sematic/types/BUILD
  sematic/types/casting.py
  sematic/types/registry.py
  sematic/types/tests/test_registry.py
  sematic/types/type.py
  sematic/types/types/tests/test_dataclass.py
Labels: enhancement, types

#602 [3/3] Migrate notes to point to user ID instead of email
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/auth.py
  sematic/api/endpoints/notes.py
  sematic/api/endpoints/payloads.py
  sematic/api/endpoints/resolutions.py
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_auth.py
  sematic/api/endpoints/tests/test_notes.py
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/api/tests/BUILD
  sematic/api/tests/fixtures.py
  sematic/api_client.py
  sematic/config/tests/BUILD
  sematic/config/tests/fixtures.py
  sematic/config/tests/test_settings.py
  sematic/db/migrations/20230217235835_add_id_to_users.sql
  sematic/db/migrations/20230221004028_add_id_to_users.py
  sematic/db/migrations/20230221004041_swap_users.sql
  sematic/db/migrations/20230222013045_add_user_id_to_runs.sql
  sematic/db/migrations/20230223020405_add_user_id_to_notes.sql
  sematic/db/models/BUILD
  sematic/db/models/artifact.py
  sematic/db/models/edge.py
  sematic/db/models/external_resource.py
  sematic/db/models/mixins/BUILD
  sematic/db/models/mixins/__init__.py
  sematic/db/models/mixins/has_external_jobs_mixin.py
  sematic/db/models/mixins/has_user_mixin.py
  sematic/db/models/mixins/json_encodable_mixin.py
  sematic/db/models/note.py
  sematic/db/models/resolution.py
  sematic/db/models/run.py
  sematic/db/models/runs_external_resource.py
  sematic/db/models/user.py
  sematic/db/queries.py
  sematic/db/schema.sql.sqlite
  sematic/ui/src/Models.tsx
  sematic/ui/src/pipelines/NotesPanel.tsx
Labels: enhancement, db

#605 Refactors the login workflow
  sematic/ui/src/Home.tsx
  sematic/ui/src/appContext.ts
  sematic/ui/src/components/EnvironmentProvider.tsx
  sematic/ui/src/components/Shell.tsx
  sematic/ui/src/components/SideBar.tsx
  sematic/ui/src/hooks/appHooks.ts
  sematic/ui/src/hooks/httpHooks.ts
  sematic/ui/src/hooks/tests/test_appHooks.cy.tsx
  sematic/ui/src/index.tsx
  sematic/ui/src/login.tsx
  sematic/ui/src/pipelines/NotesPanel.tsx
  sematic/ui/src/pipelines/PipelineBar.tsx
  sematic/ui/src/pipelines/RunDetailsPanel.tsx
Labels: ui, housekeeping

#611 Sort run tree nodes
  sematic/ui/package-lock.json
  sematic/ui/package.json
  sematic/ui/src/components/tests/test_RunStateChip.cy.tsx
  sematic/ui/src/hooks/graphHooks.ts
  sematic/ui/src/hooks/tests/test_graphHooks.cy.tsx
  sematic/ui/tests/fixtures/run.ts
  sematic/ui/tests/package.json
  sematic/ui/tests/support/utils.ts
  sematic/ui/tsconfig.json
Labels: bug, ui
