Repository sematic-ai/sematic, pull requests merged in 2023-10, with the labels that each got.

#1065 Switch runs and pipelines panels
  sematic/ui/packages/common/src/pages/Home/index.tsx
Labels: ui, usability

#1066 Link dev guide from main readme
  README.md
Labels: documentation

#1064 Capability of mounting underlying node paths in the pod
  developer-docs/README.md
  docs/api.md
  docs/cli.md
  docs/cloud-runner.md
  helm/sematic-server/templates/configmap.yaml
  helm/sematic-server/values.yaml
  sematic/__init__.py
  sematic/config/server_settings.py
  sematic/examples/testing_pipeline/__main__.py
  sematic/examples/testing_pipeline/pipeline.py
  sematic/examples/testing_pipeline/requirements.txt
  sematic/resolvers/resource_requirements.py
  sematic/resolvers/tests/test_resource_requirements.py
  sematic/scheduling/kubernetes.py
  sematic/scheduling/tests/test_kubernetes.py
Labels: enhancement, infrastructure

#1078 Bump versions for v0.35.0
  README.md
  README.rst
  docs/changelog.md
  helm/sematic-server/Chart.yaml
  sematic/versions.py
  sematic/wheel_constants.bzl
Labels: release

#1081 Update upgrade docs for dedicated SocketIO deployment
  docs/upgrades.md
Labels: documentation, infrastructure
