Repository sematic-ai/sematic, pull requests merged in 2023-09, with the labels that each got.

#1052 Have the cancel CLI use the API from the config
  sematic/cli/cancel.py
Labels: bug, cli, usability

#1054 Make run retrieval API more robust
  sematic/api_client.py
  sematic/tests/BUILD
  sematic/tests/test_api_client.py
Labels: bug

#1055 Allow custom image pull secrets
  docs/cli.md
  helm/sematic-server/templates/configmap.yaml
  helm/sematic-server/values.yaml
  sematic/config/server_settings.py
  sematic/scheduling/kubernetes.py
  sematic/scheduling/tests/test_kubernetes.py
Labels: enhancement, infrastructure

#1056 Helm chart improvements to add support for GCP
  helm/sematic-server/templates/NOTES.txt
  helm/sematic-server/templates/frontend-config.yaml
  helm/sematic-server/templates/ingress.yaml
  helm/sematic-server/templates/service.yaml
  helm/sematic-server/templates/tests/test-connection.yaml
  helm/sematic-server/values.yaml
Labels: enhancement, infrastructure

#1057 Fix PyYaml dependency errors
  requirements/requirements.in
  requirements/requirements3_10.txt
  requirements/requirements3_8.txt
  requirements/requirements3_9.txt
Labels: bug, build

#1058 Fix error in version CLI command when Server unreachable
  sematic/api_client.py
  sematic/cli/version.py
Labels: bug, cli, usability

#1061 Trivial fix incorrect parameter documentation
  docs/container-images.md
Labels: bug, documentation
