Repository sematic-ai/sematic, pull requests merged in 2023-06, with the labels that each got.

#870 Fix Native Docker Build System recursive globbing
  sematic/plugins/building/docker_builder.py
  sematic/plugins/building/tests/BUILD
  sematic/plugins/building/tests/fixtures/absolute_data.yaml
  sematic/plugins/building/tests/fixtures/absolute_image_script.yaml
  sematic/plugins/building/tests/fixtures/absolute_requirements.yaml
  sematic/plugins/building/tests/fixtures/absolute_src.yaml
  sematic/plugins/building/tests/fixtures/bad_version.yaml
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.full
  sematic/plugins/building/tests/fixtures/good_launch_script.yaml
  sematic/plugins/building/tests/fixtures/jailbreak_data.yaml
  sematic/plugins/building/tests/fixtures/jailbreak_image_script.yaml
  sematic/plugins/building/tests/fixtures/jailbreak_requirements.yaml
  sematic/plugins/building/tests/fixtures/jailbreak_src.yaml
  sematic/plugins/building/tests/fixtures/malformed_push_empty_registry.yaml
  sematic/plugins/building/tests/fixtures/malformed_push_missing_repository.yaml
  sematic/plugins/building/tests/fixtures/malformed_uri.yaml
  sematic/plugins/building/tests/fixtures/nested/ignored.yaml
  sematic/plugins/building/tests/fixtures/nested/launch_script.yaml
  sematic/plugins/building/tests/fixtures/nested/sematic_build.yaml
  sematic/plugins/building/tests/fixtures/nested/third_level/third_level.txt
  sematic/plugins/building/tests/fixtures/no_image.yaml
  sematic/plugins/building/tests/fixtures/two_images.yaml
  sematic/plugins/building/tests/test_docker_builder.py
  sematic/plugins/building/tests/test_docker_builder_config.py
Labels: bug, build

#859 [8/N] Store run command and build config
  sematic/cli/run.py
  sematic/db/migrations/20230526141354_add_run_command_and_config_to_resolutions.sql
  sematic/db/models/factories.py
  sematic/db/models/resolution.py
  sematic/db/models/tests/test_factories.py
  sematic/db/schema.sql.sqlite
  sematic/db/tests/fixtures.py
  sematic/plugins/abstract_builder.py
  sematic/plugins/building/docker_builder.py
  sematic/plugins/building/docker_builder_config.py
  sematic/plugins/building/tests/fixtures/good_launch_script.py
  sematic/plugins/building/tests/test_docker_builder.py
  sematic/resolvers/BUILD
  sematic/resolvers/local_resolver.py
  sematic/scheduling/tests/test_job_scheduler.py
Labels: db, build

#872 Remove redundant pod argument
  sematic/resolvers/local_resolver.py
  sematic/resolvers/tests/test_cloud_resolver.py
  sematic/resolvers/worker.py
Labels: housekeeping, infrastructure

#873 Expose all K8 classes in base init
  sematic/__init__.py
Labels: usability

#878 Update mypy version to avoid bug
  requirements/ci-requirements.txt
Labels: bug, ci

#857 Add build config files for Ray example pipelines
  sematic/ee/extras.bzl
  sematic/examples/cifar_classifier/BUILD
  sematic/examples/cifar_classifier/README.md
  sematic/examples/cifar_classifier/main.yaml
  sematic/examples/cifar_classifier/requirements.txt
  sematic/examples/lightning_resnet/BUILD
  sematic/examples/lightning_resnet/README.md
  sematic/examples/lightning_resnet/main.yaml
  sematic/examples/lightning_resnet/requirements.txt
  sematic/examples/testing_pipeline/README.md
  sematic/examples/testing_pipeline/__main__.yaml
  sematic/examples/testing_pipeline/requirements.txt
Labels: examples, build

#874 Optimize Native Docker builds temporally and spatially
  sematic/examples/mnist/pytorch/__main__.yaml
  sematic/examples/mnist/pytorch/mnist_learning_rates.yaml
  sematic/examples/mnist/pytorch/mnist_train.yaml
  sematic/examples/mnist/pytorch/requirements.txt
  sematic/examples/template/requirements.txt
  sematic/plugins/building/docker_builder.py
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.basic
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.data
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.full
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.requirements
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.src
  sematic/plugins/building/tests/fixtures/docker/Dockerfile.target
  sematic/plugins/building/tests/test_docker_builder.py
  sematic/utils/spinner.py
Labels: usability, build

#882 Fix Server image size bloat
  tools/sematic_wheel_rule.bzl
Labels: bug, ci, build

#881 Switch to an ASGI compliant server for remote websockets
  BUILD
  docker/Dockerfile.server
  helm/sematic-server/templates/deployment.yaml
  helm/sematic-server/templates/socketio_deployment.yaml
  helm/sematic-server/values.yaml
  requirements/requirements.in
  requirements/requirements3_10.txt
  requirements/requirements3_8.txt
  requirements/requirements3_9.txt
  sematic.pth
  sematic/BUILD
  sematic/api/BUILD
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/auth.py
  sematic/api/endpoints/events.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/api/server.py
  sematic/api/tests/fixtures.py
  sematic/api/wsgi.py
  sematic/cli/main.py
  sematic/cli/start.py
  sematic/utils/BUILD
  sematic/utils/daemonize.py
Labels: tech debt

#887 Support filter runs by tags
  sematic/ui/packages/common/src/ApiContracts.ts
  sematic/ui/packages/common/src/hooks/runHooks.ts
  sematic/ui/packages/common/src/pages/RunSearch/RunList.tsx
  sematic/ui/packages/common/src/pages/RunSearch/SearchFilters.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/TagsFilterSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/common.ts
Labels: ui

#894 Upgrade pytorch to 1.13.1
  docs/errors.md
  requirements/requirements.in
  requirements/requirements3_10.txt
  requirements/requirements3_8.txt
  requirements/requirements3_9.txt
  sematic/BUILD
  sematic/resolvers/worker.py
  sematic/torch_patch.py
  sematic/types/types/pytorch/BUILD
  sematic/types/types/pytorch/__init__.py
  tools/pytest_runner.py
  tools/sematic_rules.bzl
Labels: housekeeping

#896 Use in operator for the run search filters
  sematic/ui/packages/common/src/ApiContracts.ts
  sematic/ui/packages/common/src/hooks/runHooks.ts
  sematic/ui/packages/common/src/pages/RunSearch/filters/common.ts
Labels: ui, housekeeping

#824 [7/N] Metrics support – run user metrics
  sematic/abstract_system_metric.py
  sematic/api/endpoints/metrics.py
  sematic/api/server.py
  sematic/ee/extras.bzl
  sematic/ee/metrics.py
  sematic/ee/tests/test_metrics.py
  sematic/examples/add/pipeline.py
  sematic/examples/mnist/pytorch/BUILD
  sematic/examples/mnist/pytorch/mnist_train.py
  sematic/examples/mnist/pytorch/train_eval.py
  sematic/metrics/metric_point.py
  sematic/plugins/metrics_storage/sql/sql_metrics_storage.py
  sematic/ui/package-lock.json
  sematic/ui/packages/common/src/ApiContracts.ts
  sematic/ui/packages/common/src/Models.ts
  sematic/ui/packages/common/src/constants.ts
  sematic/ui/packages/common/src/hooks/metricsHooks.ts
  sematic/ui/packages/main/package.json
  sematic/ui/packages/main/src/Payloads.tsx
  sematic/ui/packages/main/src/components/Metrics.tsx
  sematic/ui/packages/main/src/pipelines/PipelineBar.tsx
  sematic/ui/packages/main/src/pipelines/RunMetricsPanel.tsx
  sematic/ui/packages/main/src/pipelines/RunTabs.tsx
  sematic/ui/packages/main/src/sockets.ts
  sematic/ui/packages/main/src/utils.tsx
Labels: ui, metrics

#888 Add hacker news summarization example
  requirements/requirements.in
  requirements/requirements3_10.txt
  requirements/requirements3_8.txt
  requirements/requirements3_9.txt
  sematic/cli/BUILD
  sematic/examples/hackernews_summarization/.gitignore
  sematic/examples/hackernews_summarization/AUTHORS
  sematic/examples/hackernews_summarization/BUILD
  sematic/examples/hackernews_summarization/README.md
  sematic/examples/hackernews_summarization/__init__.py
  sematic/examples/hackernews_summarization/__main__.py
  sematic/examples/hackernews_summarization/output.png
  sematic/examples/hackernews_summarization/pipeline.py
  sematic/examples/hackernews_summarization/requirements.txt
  sematic/examples/hackernews_summarization/template.html
Labels: examples

#900 Get rid of leftover "glow" files
  docs/source/glow.api.endpoints.rst
  docs/source/glow.api.rst
  docs/source/glow.api.tests.rst
  docs/source/glow.db.models.rst
  docs/source/glow.db.rst
  docs/source/glow.db.tests.rst
  docs/source/glow.examples.add.rst
  docs/source/glow.examples.rst
  docs/source/glow.resolvers.rst
  docs/source/glow.rst
  docs/source/glow.types.rst
  docs/source/glow.types.types.rst
  docs/source/glow.utils.rst
  sematic/ui/packages/main/public/glow.png
Labels: housekeeping

#901 Scrub cleaner logs
  docs/deploy.md
  sematic/config/config.py
  sematic/config/tests/BUILD
  sematic/config/tests/test_config.py
Labels: security

#902 Fix matplotlib viz
  sematic/ui/packages/common/src/typeViz/vizMapping.ts
  sematic/ui/packages/main/src/types/Types.tsx
Labels: bug, ui, types

#907 Add new IDEA project config files to gitignore
  .gitignore
Labels: housekeeping

#909 Release v0.31.0
  README.md
  README.rst
  docs/changelog.md
  docs/upgrades.md
  helm/sematic-server/Chart.yaml
  sematic/versions.py
  sematic/wheel_constants.bzl
Labels: release

#895 Context menus on the run details page
  sematic/ui/packages/common/src/component/ContextMenu.tsx
  sematic/ui/packages/common/src/component/MoreVertButton.tsx
  sematic/ui/packages/common/src/hooks/resolutionHooks.ts
  sematic/ui/packages/common/src/hooks/runHooks.ts
  sematic/ui/packages/common/src/pages/RunDetails/FunctionSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/PipelineSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/artifacts/artifact.tsx
  sematic/ui/packages/common/src/pages/RunDetails/contextMenus/ArtifactMenu.tsx
  sematic/ui/packages/common/src/pages/RunDetails/contextMenus/FunctionSectionMenu.tsx
  sematic/ui/packages/common/src/pages/RunDetails/contextMenus/PipelineSectionMenu.tsx
  sematic/ui/packages/common/src/pages/RunDetails/contextMenus/RunSectionMenu.tsx
  sematic/ui/packages/common/src/theme/new/components.ts
Labels: ui

#899 Dagview selection
  sematic/ui/packages/common/src/pages/RunDetails/dag/CompoundNode.tsx
  sematic/ui/packages/common/src/pages/RunDetails/dag/LeafNode.tsx
  sematic/ui/packages/common/src/pages/RunDetails/dag/ReactFlowDag.tsx
  sematic/ui/packages/common/src/pages/RunDetails/dag/common.ts
  sematic/ui/packages/common/src/pages/RunDetails/dag/dagLayout.ts
Labels: ui

#898 Logs in the new dashboard
  sematic/ui/packages/common/src/ApiContracts.ts
  sematic/ui/packages/common/src/hooks/logHooks.ts
  sematic/ui/packages/common/src/hooks/scrollingHooks.ts
  sematic/ui/packages/common/src/layout/ThreeColumns.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunTabs.tsx
  sematic/ui/packages/common/src/pages/RunDetails/logs/BidirectionalLogView.tsx
  sematic/ui/packages/common/src/pages/RunDetails/logs/LogsPane.tsx
  sematic/ui/packages/main/src/hooks/scrollingHooks.ts
  sematic/ui/packages/main/src/pipelines/LogPanel.tsx
Labels: ui

#910 Add requirements for Hugging Face
  requirements/requirements.in
  requirements/requirements3_10.txt
  requirements/requirements3_8.txt
  requirements/requirements3_9.txt
Labels: housekeeping, build

#919 Add background color to side panels
  sematic/ui/packages/common/src/component/menu.tsx
  sematic/ui/packages/common/src/layout/ThreeColumns.tsx
  sematic/ui/packages/common/src/muitypes.d.ts
  sematic/ui/packages/common/src/pages/RunDetails/MetaDataPane.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunTreeSection.tsx
  sematic/ui/packages/common/src/theme/new/palette.ts
Labels: ui

#918 Getting started page (new dashboard version)
  sematic/ui/packages/common/src/component/ShellCommand.tsx
  sematic/ui/packages/common/src/component/menu.tsx
  sematic/ui/packages/common/src/pages/GettingStarted/index.tsx
  sematic/ui/packages/common/src/theme/new/components.ts
  sematic/ui/packages/main/src/index.tsx
Labels: ui

#916 Mention helm update in release/upgrade docs
  developer-docs/README.md
  docs/upgrades.md
Labels: documentation, infrastructure

#925 Adapt run metrics panel to the new dashboard
  sematic/ui/packages/common/src/pages/RunDetails/RunTabs.tsx
  sematic/ui/packages/common/src/pages/RunDetails/metrics/Metrics.tsx
  sematic/ui/packages/common/src/pages/RunDetails/metrics/MetricsPane.tsx
  sematic/ui/packages/common/src/pages/RunDetails/metrics/index.tsx
  sematic/ui/packages/common/src/sockets.ts
  sematic/ui/packages/common/src/utils/color.ts
  sematic/ui/packages/main/src/pipelines/RunMetricsPanel.tsx
  sematic/ui/packages/main/src/sockets.ts
  sematic/ui/packages/main/src/utils.tsx
Labels: ui

#924 [New Dashboard] Hook up the notifications with snack message
  sematic/ui/packages/common/src/context/SnackBarContext.ts
  sematic/ui/packages/common/src/context/SnackBarProvider.tsx
  sematic/ui/packages/common/src/hooks/pipelineSocketMonitorHooks.tsx
  sematic/ui/packages/common/src/hooks/runHooks.ts
  sematic/ui/packages/common/src/pages/PipelineList/LatestRunsColumn.tsx
  sematic/ui/packages/common/src/pages/PipelineList/PipelineList.tsx
  sematic/ui/packages/common/src/pages/PipelineRuns/index.tsx
  sematic/ui/packages/common/src/pages/RunDetails/FunctionSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx
  sematic/ui/packages/main/src/pipelines/PipelineBar.tsx
  sematic/ui/packages/main/src/pipelines/PipelineIndex.tsx
  sematic/ui/packages/main/src/sockets.ts
Labels: ui

#927 Adapt external resources panel to the new dashboard
  sematic/ui/packages/common/src/hooks/externalResourceHooks.ts
  sematic/ui/packages/common/src/pages/RunDetails/RunTabs.tsx
  sematic/ui/packages/common/src/pages/RunDetails/externalResource/ExternalResource.tsx
  sematic/ui/packages/common/src/pages/RunDetails/externalResource/ExternalResourceState.tsx
  sematic/ui/packages/common/src/pages/RunDetails/externalResource/index.tsx
  sematic/ui/packages/main/src/pipelines/external_resource/ExternalResource.tsx
Labels: ui

#926 Adapt source code panel to the new dashboard
  sematic/ui/packages/common/src/pages/RunDetails/RunTabs.tsx
  sematic/ui/packages/common/src/pages/RunDetails/sourcecode/SourceCode.tsx
  sematic/ui/packages/common/src/pages/RunDetails/sourcecode/index.tsx
  sematic/ui/packages/main/src/components/SourceCode.tsx
Labels: ui

#935 [New dashboard] Show exception message when run failed in output pane
  sematic/ui/packages/common/src/component/Exception.tsx
  sematic/ui/packages/common/src/pages/RunDetails/artifacts/OutputPane.tsx
  sematic/ui/packages/main/src/pipelines/OutputPanel.tsx
Labels: ui

#937 Add ways to switch between two UI modes
  sematic/ui/packages/common/src/component/UserMenu.tsx
  sematic/ui/packages/main/src/components/SideBar.tsx
Labels: ui

#933 Render pipeline metrics in the new Dashboard
  sematic/ui/packages/common/src/component/ImportPath.tsx
  sematic/ui/packages/common/src/pages/PipelineRuns/PipelineInfoPane.tsx
  sematic/ui/packages/common/src/pages/PipelineRuns/index.tsx
  sematic/ui/packages/common/src/pages/RunDetails/CenterPane.tsx
  sematic/ui/packages/common/src/pages/RunDetails/MetaDataPane.tsx
  sematic/ui/packages/common/src/pages/RunDetails/PipelineSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunTabs.tsx
  sematic/ui/packages/common/src/pages/RunDetails/contextMenus/PipelineSectionMenu.tsx
  sematic/ui/packages/common/src/pages/RunDetails/metricsTab/Metrics.tsx
  sematic/ui/packages/common/src/pages/RunDetails/metricsTab/MetricsPane.tsx
  sematic/ui/packages/common/src/pages/RunDetails/metricsTab/index.tsx
  sematic/ui/packages/common/src/pages/RunDetails/pipelineMetrics/BasicMetricsPanel.tsx
  sematic/ui/packages/common/src/pages/RunDetails/pipelineMetrics/index.tsx
  sematic/ui/packages/main/src/pipelines/BasicMetricsPanel.tsx
  sematic/ui/packages/main/src/pipelines/RunMetricsPanel.tsx
Labels: ui, metrics

#938 Fixes a bug when function path is none
  sematic/db/queries.py
Labels: bug

#930 Metrics docs
  docs/api.md
  docs/images/liveMetrics.png
  docs/metrics.md
  sematic/plugins/metrics_storage/sql/sql_metrics_storage.py
Labels: documentation, metrics

#941 Update deploy.md
  docs/deploy.md
Labels: documentation
