Repository sematic-ai/sematic, pull requests merged in 2023-01, with the labels that each got.

#429 Move(rename) some UI files for better organization.
  sematic/ui/src/hooks/graphHooks.ts
  sematic/ui/src/pipelines/Artifacts.tsx
  sematic/ui/src/pipelines/LogPanel.tsx
  sematic/ui/src/pipelines/MenuPanel.tsx
  sematic/ui/src/pipelines/NotesPanel.tsx
  sematic/ui/src/pipelines/PipelineBar.tsx
  sematic/ui/src/pipelines/PipelinePanels.tsx
  sematic/ui/src/pipelines/PipelineRunView.tsx
  sematic/ui/src/pipelines/RunDetailsPanel.tsx
  sematic/ui/src/pipelines/RunPanel.tsx
  sematic/ui/src/pipelines/RunTabs.tsx
  sematic/ui/src/pipelines/RunTree.tsx
  sematic/ui/src/pipelines/ScrollingLogView.tsx
  sematic/ui/src/pipelines/graph/ArtifactNode.tsx
  sematic/ui/src/pipelines/graph/ReactFlowDag.tsx
  sematic/ui/src/pipelines/graph/RunNode.tsx
  sematic/ui/src/pipelines/graph/graphContext.ts
Labels: ui, housekeeping

#342 Update make_artifact to use value type for Union
  sematic/db/models/factories.py
  sematic/db/models/tests/test_factories.py
  sematic/types/types/union.py
Labels: bug, ui, types

#351 Helm chart fix and refactor
  helm/sematic-server/Chart.yaml
  helm/sematic-server/templates/NOTES.txt
  helm/sematic-server/templates/_helpers.tpl
  helm/sematic-server/templates/configmap.yaml
  helm/sematic-server/templates/deployment.yaml
  helm/sematic-server/templates/hpa.yaml
  helm/sematic-server/templates/ingress.yaml
  helm/sematic-server/templates/secret.yaml
  helm/sematic-server/templates/server-role-binding.yaml
  helm/sematic-server/templates/server-role.yaml
  helm/sematic-server/templates/service.yaml
  helm/sematic-server/templates/serviceaccount.yaml
  helm/sematic-server/templates/tests/test-connection.yaml
  helm/sematic-server/values.yaml
Labels: bug, tech debt, infrastructure

#435 Compute cache key only for resolved args
  sematic/caching/caching.py
  sematic/caching/tests/BUILD
  sematic/caching/tests/test_caching.py
Labels: bug

#413 Fixes UI error in case of exception
  sematic/ui/src/hooks/scrollingHooks.ts
  sematic/ui/src/pipelines/LogPanel.tsx
  sematic/ui/src/pipelines/ScrollingLogView.tsx
Labels: bug, ui

#433 Implement deep link for selected runs
  sematic/ui/package-lock.json
  sematic/ui/package.json
  sematic/ui/src/hooks/pipelineHooks.ts
  sematic/ui/src/pipelines/NotesPanel.tsx
  sematic/ui/src/pipelines/PipelinePanels.tsx
  sematic/ui/src/pipelines/PipelinePanelsContext.tsx
  sematic/ui/src/pipelines/RunDetailsPanel.tsx
  sematic/ui/src/pipelines/RunTree.tsx
  sematic/ui/src/pipelines/graph/ReactFlowDag.tsx
Labels: enhancement, ui, usability

#426 Add functionality to click artifacts in the DAG view
  sematic/ui/src/pipelines/Artifacts.tsx
  sematic/ui/src/pipelines/PipelinePanels.tsx
  sematic/ui/src/pipelines/PipelinePanelsContext.tsx
  sematic/ui/src/pipelines/RunTabs.tsx
  sematic/ui/src/pipelines/RunTree.tsx
  sematic/ui/src/pipelines/graph/ReactFlowDag.tsx
Labels: enhancement, ui

#436 Avoids unnecessary unmount that causes screen flashing
  sematic/ui/src/pipelines/MenuPanel.tsx
  sematic/ui/src/pipelines/PipelinePanels.tsx
Labels: bug, ui

#437 Support link for nested run
  sematic/ui/src/pipelines/PipelineRunView.tsx
Labels: enhancement, ui

#434 [3/N] Storage plugins integration
  helm/sematic-server/templates/configmap.yaml
  sematic/BUILD
  sematic/api/endpoints/artifacts.py
  sematic/api/endpoints/tests/test_artifacts.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/api/tests/fixtures.py
  sematic/api_client.py
  sematic/cli/tests/test_logs.py
  sematic/db/models/BUILD
  sematic/db/models/factories.py
  sematic/db/models/tests/test_factories.py
  sematic/db/tests/BUILD
  sematic/db/tests/fixtures.py
  sematic/db/tests/test_queries.py
  sematic/graph.py
  sematic/log_reader.py
  sematic/plugins/abstract_storage.py
  sematic/plugins/storage/local_storage.py
  sematic/plugins/storage/memory_storage.py
  sematic/plugins/storage/tests/test_local_storage.py
  sematic/plugins/storage/tests/test_memory_storage.py
  sematic/resolvers/BUILD
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/log_streamer.py
  sematic/resolvers/tests/BUILD
  sematic/resolvers/tests/fixtures.py
  sematic/resolvers/tests/test_cloud_resolver.py
  sematic/resolvers/tests/test_local_resolver.py
  sematic/resolvers/tests/test_worker.py
  sematic/resolvers/worker.py
  sematic/tests/BUILD
  sematic/tests/fixtures.py
  sematic/tests/test_api_client.py
  sematic/tests/test_graph.py
  sematic/types/types/pandas/tests/test_dataframe.py
  sematic/utils/retry.py
Labels: enhancement

#444 [Bug] Fixes an issue that not being able to unmount a component causes unnecessary complexity in the downstream processing.
  sematic/ui/src/pipelines/PipelineRunView.tsx
Labels: bug, ui

#440 Fixes a bug on websocket graph reactive callbacks.
  sematic/ui/src/hooks/graphHooks.ts
Labels: bug, ui

#446 Fix lint error
  sematic/graph.py
Labels: bug, housekeeping, ci

#450 Explicitly call out client upgrade in the release docs
  developer-docs/README.md
Labels: documentation, usability

#451 Fixes all typescript lint errors
  sematic/ui/src/addons/grafana/GrafanaPanel.tsx
  sematic/ui/src/components/CopyButton.tsx
  sematic/ui/src/components/RunStateChip.tsx
  sematic/ui/src/components/RunTime.tsx
  sematic/ui/src/components/SideBar.tsx
  sematic/ui/src/hooks/scrollingHooks.ts
  sematic/ui/src/index.tsx
  sematic/ui/src/pipelines/LogPanel.tsx
  sematic/ui/src/pipelines/NotesPanel.tsx
  sematic/ui/src/pipelines/PipelineBar.tsx
  sematic/ui/src/pipelines/PipelineRunView.tsx
  sematic/ui/src/pipelines/ScrollingLogView.tsx
  sematic/ui/src/runs/RunView.tsx
  sematic/ui/src/types/Types.tsx
Labels: ui, housekeeping

#448 Setup Circle CI run for ESLINT
  .circleci/config.yml
  sematic/ui/package.json
Labels: enhancement, infrastructure

#453 Ability to expand the shared memory on worker pods
  docs/execution-modes.md
  sematic/examples/testing_pipeline/__main__.py
  sematic/examples/testing_pipeline/pipeline.py
  sematic/resolvers/resource_requirements.py
  sematic/resolvers/tests/test_resource_requirements.py
  sematic/scheduling/kubernetes.py
  sematic/scheduling/tests/test_kubernetes.py
Labels: enhancement, scaling, infrastructure

#456 Remove incorrect options from migrate CLI commands
  sematic/db/migrate.py
Labels: bug, cli

#461 Warn about Sqlite3 version only when used
  sematic/config/BUILD
  sematic/config/config.py
  sematic/versions.py
Labels: db, usability

#439 Enable using Ray from bazel produced Docker image
  Makefile
  WORKSPACE
  bazel/BUILD
  bazel/bazel_python
  bazel/pipeline.bzl
  bazel/ray
  docker/Dockerfile.worker
  docs/container-images.md
  requirements/BUILD
  requirements/requirements.in
  requirements/requirements.txt
  requirements/requirements38.txt
  requirements/requirements39.txt
  sematic/examples/testing_pipeline/BUILD
  sematic/examples/testing_pipeline/__main__.py
  sematic/examples/testing_pipeline/pipeline.py
  sematic/examples/testing_pipeline/requirements.txt
  sematic/resolvers/tests/test_worker.py
  sematic/resolvers/worker.py
  tools/sematic_wheel_rule.bzl
Labels: enhancement, infrastructure

#457 Fix schema dump relative file path usage
  sematic/db/migrate.py
Labels: bug, cli

#425 Use external resources with cloud resolver
  helm/sematic-server/values.yaml
  sematic/api/endpoints/external_resources.py
  sematic/api/endpoints/meta.py
  sematic/api/endpoints/tests/test_external_resources.py
  sematic/api_client.py
  sematic/plugins/abstract_external_resource.py
  sematic/plugins/external_resource/timed_message.py
  sematic/resolver.py
  sematic/resolvers/BUILD
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/resource_managers/server_manager.py
  sematic/resolvers/resource_managers/tests/test_server_manager.py
  sematic/resolvers/silent_resolver.py
  sematic/resolvers/state_machine_resolver.py
  sematic/resolvers/tests/test_silent_resolver.py
Labels: enhancement

#466 Revert "Remove incorrect options from migrate CLI commands (#456)"
  sematic/db/migrate.py
Labels: bug, cli

#469 Prevents getting infinite loops with useEffect()
  sematic/ui/src/pipelines/NotesPanel.tsx
Labels: bug, ui

#463 Deeplink for run tabs
  sematic/ui/src/hooks/pipelineHooks.ts
  sematic/ui/src/pipelines/PipelinePanels.tsx
  sematic/ui/src/pipelines/RunTree.tsx
  sematic/ui/src/utils.tsx
Labels: enhancement, ui

#465 Documentation refresh
  README.md
  docs/README.md
  docs/SUMMARY.md
  docs/api.md
  docs/capabilities.md
  docs/cloud-resolver.md
  docs/concepts.md
  docs/first-pipeline.md
  docs/functions.md
  docs/get-started.md
  docs/glossary.md
  docs/local-execution.md
  docs/real-example.md
  docs/type-support.md
  docs/types.md
  sematic/future_context.py
  sematic/resolver.py
  sematic/resolvers/resource_requirements.py
  sematic/resolvers/tests/test_type_utils.py
  sematic/resolvers/type_utils.py
Labels: documentation

#471 [bugfix] Fix corrupted settings files from 0.21.1
  sematic/cli/BUILD
  sematic/cli/cli.py
  sematic/cli/main.py
  sematic/cli/migrate.py
  sematic/db/migrations/20221214142609_plugin_settings_file.py
  sematic/resolver.py
Labels: bug

#468 Release 0.22.0
  Makefile
  README.md
  README.rst
  developer-docs/README.md
  docs/changelog.md
  helm/sematic-server/Chart.yaml
  sematic/versions.py
  sematic/wheel_version.bzl
Labels: release

#473 Fix team link on user documentation
  docs/README.md
Labels: documentation

#470 Ability to order model results on backend endpoints
  sematic/api/endpoints/artifacts.py
  sematic/api/endpoints/edges.py
  sematic/api/endpoints/notes.py
  sematic/api/endpoints/request_parameters.py
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/api_client.py
Labels: enhancement, db

#474 More robust fix for old settings files
  sematic/db/migrations/20221214142609_plugin_settings_file.py
Labels: bug, cli

#475 Release v0.22.1
  docs/changelog.md
  helm/sematic-server/Chart.yaml
  sematic/versions.py
  sematic/wheel_version.bzl
Labels: release

#476 Update release procedure
  developer-docs/README.md
Labels: documentation, enhancement, infrastructure

#478 Helm release fixes
  developer-docs/README.md
  helm/sematic-server/Chart.yaml
  helm/sematic-server/templates/service.yaml
Labels: bug, infrastructure

#414 Function Output Caching
  docs/changelog.md
  sematic/abstract_future.py
  sematic/calculator.py
  sematic/db/migrations/20230105163857_add_run_cache_key.sql
  sematic/db/migrations/20230105170402_add_resolution_cache_namespace.sql
  sematic/db/models/factories.py
  sematic/db/models/resolution.py
  sematic/db/models/run.py
  sematic/db/schema.sql.sqlite
  sematic/db/tests/fixtures.py
  sematic/examples/testing_pipeline/__main__.py
  sematic/examples/testing_pipeline/pipeline.py
  sematic/future.py
  sematic/resolvers/BUILD
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/silent_resolver.py
  sematic/resolvers/state_machine_resolver.py
  sematic/resolvers/worker.py
  sematic/tests/test_future.py
Labels: enhancement, db

#484 Enable dataclass compatibility
  sematic/types/types/dataclass.py
  sematic/types/types/tests/test_dataclass.py
Labels: tech debt

#489 Provide default plugin settings
  sematic/config/settings.py
  sematic/config/tests/BUILD
  sematic/config/tests/fixtures.py
  sematic/config/tests/test_server_settings.py
  sematic/config/tests/test_settings.py
  sematic/config/tests/test_user_settings.py
Labels: bug, cli

#481 Add support for Bazel 6.0.0
  bazel/WORKSPACE
Labels: enhancement, infrastructure

#467 Kuberay wrapper plugin
  sematic/plugins/BUILD
  sematic/plugins/abstract_kuberay_wrapper.py
  sematic/plugins/kuberay_wrapper/BUILD
  sematic/plugins/kuberay_wrapper/standard.py
  sematic/plugins/kuberay_wrapper/tests/BUILD
  sematic/plugins/kuberay_wrapper/tests/test_standard.py
  sematic/utils/exceptions.py
Labels: enhancement, infrastructure

#487 Add a link in output panel pointing to logs panel in case of error
  sematic/ui/src/pipelines/OutputPanel.tsx
Labels: enhancement, ui

#479 Show cloned run state
  sematic/ui/src/Home.tsx
  sematic/ui/src/components/CopyButton.tsx
  sematic/ui/src/components/Notes.tsx
  sematic/ui/src/components/RunId.tsx
  sematic/ui/src/components/RunStateChip.tsx
  sematic/ui/src/pipelines/PipelineBar.tsx
  sematic/ui/src/pipelines/PipelineIndex.tsx
  sematic/ui/src/pipelines/RunDetailsPanel.tsx
  sematic/ui/src/pipelines/RunTree.tsx
  sematic/ui/src/pipelines/graph/RunNode.tsx
  sematic/ui/src/runs/RunIndex.tsx
Labels: enhancement, ui, housekeeping

#492 Add retry for data 'put'
  sematic/api_client.py
Labels: enhancement, scaling

#490 Update Helm deployment instructions
  docs/deploy.md
Labels: documentation

#499 Make _getitem importable on graph cloning
  sematic/examples/testing_pipeline/__main__.py
  sematic/examples/testing_pipeline/pipeline.py
  sematic/future_operators/getitem.py
  sematic/ui/src/constants.ts
Labels: bug

#501 Dismiss loading indicator
  sematic/ui/src/pipelines/ScrollingLogView.tsx
Labels: bug, ui

#504 Add toggle to disable Sematic log ingestion
  docs/changelog.md
  docs/cloud-resolver.md
  docs/sematic-ui.md
  sematic/config/user_settings.py
  sematic/resolvers/BUILD
  sematic/resolvers/log_streamer.py
  sematic/resolvers/tests/BUILD
  sematic/resolvers/tests/test_worker.py
  sematic/resolvers/worker.py
  sematic/utils/stdout.py
Labels: enhancement, observability

#503 Change logs polling interval
  sematic/ui/src/hooks/logHooks.ts
Labels: ui

#496 disable publishing coverage
  .circleci/config.yml
Labels: ci

#500 Support for non-deterministic cached builds in Bazel
  bazel/pipeline.bzl
  docs/container-images.md
  sematic/container_images.py
Labels: bug, infrastructure

#510 Bump release version 0.22.2
  docs/changelog.md
  helm/sematic-server/Chart.yaml
  sematic/BUILD
  sematic/versions.py
  sematic/wheel_version.bzl
Labels: release

#488 Add EE directory and license
  LICENSE
  sematic/ee/LICENSE
  sematic/ee/README.md
Labels: documentation, security

#512 Fix lint and mypy errors on main
  requirements/ci-requirements.txt
  sematic/container_images.py
Labels: housekeeping

#515 Fixes a race condition issue
  docs/changelog.md
  sematic/ui/src/hooks/graphHooks.ts
  sematic/ui/src/utils.tsx
Labels: bug, ui

#517 Upgrade aspect_bazel_lib to 1.23.3
  WORKSPACE
Labels: housekeeping, ci

#508 Slack integration Publisher plugin
  helm/sematic-server/templates/configmap.yaml
  helm/sematic-server/values.yaml
  sematic/abstract_plugin.py
  sematic/api/BUILD
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/resolutions.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/cli/BUILD
  sematic/config/server_settings.py
  sematic/plugins/BUILD
  sematic/plugins/abstract_publisher.py
  sematic/plugins/publishing/BUILD
  sematic/plugins/publishing/__init__.py
  sematic/plugins/publishing/slack.py
  sematic/plugins/publishing/tests/BUILD
  sematic/plugins/publishing/tests/test_slack.py
  sematic/resolvers/tests/BUILD
  sematic/resolvers/tests/test_worker.py
  sematic/tests/BUILD
  sematic/tests/fixtures.py
  sematic/tests/utils.py
Labels: enhancement, observability

#472 Implements UI for external resource
  sematic/ui/src/Models.tsx
  sematic/ui/src/hooks/externalResourceHooks.ts
  sematic/ui/src/hooks/httpHooks.ts
  sematic/ui/src/hooks/runDetailsHooks.ts
  sematic/ui/src/pipelines/DocumentationPanel.tsx
  sematic/ui/src/pipelines/RunTabs.tsx
  sematic/ui/src/pipelines/ScrollingLogView.tsx
  sematic/ui/src/pipelines/external_resource/ExternalResource.tsx
  sematic/ui/src/pipelines/external_resource/ExternalResourceState.tsx
Labels: enhancement, ui
