Repository sematic-ai/sematic, pull requests merged in 2023-03, with the labels that each got.

#614 `S3Location` and `S3Bucket` types
  sematic/types/BUILD
  sematic/types/types/aws/BUILD
  sematic/types/types/aws/__init__.py
  sematic/types/types/aws/s3.py
  sematic/types/types/aws/tests/BUILD
  sematic/types/types/aws/tests/test_s3.py
  sematic/ui/src/s3.png
  sematic/ui/src/types/Types.tsx
  sematic/ui/tests/fixtures/run.ts
Labels: enhancement, ui, types

#613 Remove hash from URL in telemetry
  sematic/ui/src/index.tsx
Labels: ui, tech debt

#615 Refactor table structure and add `user` column
  sematic/ui/src/components/RunList.tsx
  sematic/ui/src/hooks/domHooks.ts
  sematic/ui/src/pipelines/PipelineIndex.tsx
  sematic/ui/src/runs/RunIndex.tsx
  sematic/ui/tests/e2e/main.cy.ts
Labels: ui, housekeeping, usability

#618 Add run owner info on the run details page
  sematic/ui/src/pipelines/PipelineBar.tsx
  sematic/ui/src/tests/test_utils.cy.ts
  sematic/ui/src/utils.tsx
  sematic/ui/tests/fixtures/user.ts
Labels: enhancement, ui

#625 Fix pandas docs
  docs/images/DataFrame.png
  docs/types.md
Labels: documentation

#620 Log message to be used for pipeline stats
  sematic/api/endpoints/resolutions.py
Labels: observability

#624 Support deep linking to selected panels on the run details page
  sematic/ui/src/hooks/pipelineHooks.ts
  sematic/ui/src/pipelines/NotesPanel.tsx
  sematic/ui/src/pipelines/PipelinePanels.tsx
  sematic/ui/src/pipelines/RunPanel.tsx
Labels: bug, enhancement, ui

#627 Refactor types.tsx
  sematic/ui/src/Models.tsx
  sematic/ui/src/types/Types.tsx
  sematic/ui/src/types/boolean.tsx
  sematic/ui/src/types/common.tsx
  sematic/ui/src/types/dataclass.tsx
  sematic/ui/src/types/dataframetable.tsx
  sematic/ui/src/types/datatime.tsx
  sematic/ui/src/types/dict.tsx
  sematic/ui/src/types/enum.tsx
  sematic/ui/src/types/float.tsx
  sematic/ui/src/types/int.tsx
  sematic/ui/src/types/link.tsx
  sematic/ui/src/types/list.tsx
  sematic/ui/src/types/matplot.tsx
  sematic/ui/src/types/none.tsx
  sematic/ui/src/types/plotly.tsx
  sematic/ui/src/types/str.tsx
  sematic/ui/src/types/torchDataLoader.tsx
  sematic/ui/src/types/tuple.tsx
Labels: ui, housekeeping

#631 Fixes a bug that removes the selected tab when the page is first loaded
  sematic/ui/src/pipelines/PipelinePanels.tsx
Labels: bug, ui

#630 Add manual tag to other image targets
  bazel/pipeline.bzl
Labels: build

#633 Fixes user field name in a Note model
  sematic/api/endpoints/notes.py
  sematic/api/endpoints/tests/test_notes.py
  sematic/ui/src/Models.tsx
  sematic/ui/src/pipelines/NotesPanel.tsx
Labels: bug, ui

#636 UI Bug fix + makefile improvement
  Makefile
  sematic/ui/src/pipelines/RunTree.tsx
Labels: bug, ui

#635 Add a log spamming func to the Testing Pipeline
  sematic/examples/testing_pipeline/__main__.py
  sematic/examples/testing_pipeline/pipeline.py
Labels: examples, testing

#647 Refactor the interface of useHttpClient
  sematic/ui/src/hooks/appHooks.ts
  sematic/ui/src/hooks/externalResourceHooks.ts
  sematic/ui/src/hooks/graphHooks.ts
  sematic/ui/src/hooks/httpHooks.ts
  sematic/ui/src/hooks/logHooks.ts
  sematic/ui/src/hooks/pipelineHooks.ts
  sematic/ui/src/login.tsx
Labels: ui, housekeeping

#644 Force runs to pass through only allowed states
  sematic/abstract_future.py
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/test_notes.py
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/cli/tests/BUILD
  sematic/cli/tests/test_cancel.py
  sematic/cli/tests/test_logs.py
  sematic/db/BUILD
  sematic/db/models/tests/test_json_encodable_mixin.py
  sematic/db/queries.py
  sematic/db/tests/BUILD
  sematic/db/tests/fixtures.py
  sematic/db/tests/test_queries.py
  sematic/plugins/publishing/tests/test_slack.py
  sematic/resolvers/tests/test_cloud_resolver.py
  sematic/scheduling/job_scheduler.py
  sematic/tests/BUILD
  sematic/tests/fixtures.py
  sematic/tests/test_log_reader.py
  sematic/types/type.py
Labels: bug, reliability

#634 Filter pipelines of current user on the home page
  sematic/ui/src/Home.tsx
Labels: enhancement, ui

#649 Add ray architecture info
  docs/images/rayDiagram.png
  docs/ray.md
Labels: documentation

#623 `Image` type
  requirements/requirements.in
  requirements/requirements3_10.txt
  requirements/requirements3_8.txt
  requirements/requirements3_9.txt
  sematic/api/endpoints/storage.py
  sematic/api_client.py
  sematic/caching/caching.py
  sematic/db/models/factories.py
  sematic/db/models/tests/test_factories.py
  sematic/db/tests/fixtures.py
  sematic/plugins/storage/local_storage.py
  sematic/plugins/storage/s3_storage.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/tests/test_cloud_resolver.py
  sematic/resolvers/tests/test_worker.py
  sematic/resolvers/worker.py
  sematic/types/BUILD
  sematic/types/__init__.py
  sematic/types/registry.py
  sematic/types/serialization.py
  sematic/types/types/BUILD
  sematic/types/types/bool.py
  sematic/types/types/dataclass.py
  sematic/types/types/datetime.py
  sematic/types/types/dict.py
  sematic/types/types/enum.py
  sematic/types/types/float.py
  sematic/types/types/image.py
  sematic/types/types/integer.py
  sematic/types/types/list.py
  sematic/types/types/none.py
  sematic/types/types/pandas/dataframe.py
  sematic/types/types/pandas/tests/test_dataframe.py
  sematic/types/types/plotly/figure.py
  sematic/types/types/pytorch/dataloader.py
  sematic/types/types/pytorch/tensor.py
  sematic/types/types/snowflake/snowflake_table.py
  sematic/types/types/str.py
  sematic/types/types/tests/BUILD
  sematic/types/types/tests/test_dataclass.py
  sematic/types/types/tests/test_datetime.py
  sematic/types/types/tests/test_dict.py
  sematic/types/types/tests/test_image.py
  sematic/types/types/tests/test_list.py
  sematic/types/types/tests/test_tuple.py
  sematic/types/types/tuple.py
  sematic/types/types/union.py
  sematic/ui/package-lock.json
  sematic/ui/packages/main/src/base64ArrayBuffer.js
  sematic/ui/packages/main/src/hooks/blobHooks.ts
  sematic/ui/packages/main/src/pipelines/Artifacts.tsx
  sematic/ui/packages/main/src/types/Types.tsx
  sematic/ui/packages/main/src/types/aws.tsx
  sematic/ui/packages/main/src/types/common.tsx
  sematic/ui/packages/main/src/types/image.tsx
  sematic/ui/packages/main/src/types/s3.png
  sematic/utils/tests/test_hashing.py
Labels: enhancement, ui, types

#652 Fix S3 signatures by specifying region and signature version
  docs/upgrades.md
  helm/sematic-server/templates/configmap.yaml
  helm/sematic-server/values.yaml
  sematic/api/endpoints/storage.py
  sematic/plugins/storage/s3_storage.py
Labels: bug

#658 Clear out old storage code
  sematic/BUILD
  sematic/db/models/tests/BUILD
  sematic/storage.py
  sematic/tests/BUILD
Labels: tech debt, housekeeping

#655 Decrease CloudResolver max poll interval to 1 min
  sematic/resolvers/cloud_resolver.py
Labels: usability

#661 Add more compact ser/des for simple dataclasses
  sematic/types/types/dataclass.py
  sematic/types/types/tests/test_dataclass.py
Labels: types, usability

#667 Enforce import sorting
  Makefile
Labels: housekeeping, build

#664 Fix incorrect set command in user docs
  docs/local-execution.md
Labels: bug, documentation

#626 Handle signals in subprocesses of business logic
  sematic/examples/testing_pipeline/__main__.py
  sematic/examples/testing_pipeline/pipeline.py
  sematic/resolvers/BUILD
  sematic/resolvers/log_streamer.py
  sematic/resolvers/state_machine_resolver.py
  sematic/resolvers/tests/BUILD
  sematic/resolvers/tests/test_local_resolver.py
  sematic/resolvers/tests/test_log_streamer.py
  sematic/resolvers/worker.py
  sematic/utils/BUILD
  sematic/utils/signals.py
Labels: bug, reliability

#666 Standardize Ray external resource messages
  sematic/ee/plugins/external_resource/ray/cluster.py
Labels: usability

#670 Fix unit tests on main
  sematic/ee/plugins/external_resource/ray/tests/test_cluster.py
Labels: bug, testing, build

#665 Document zooming in the Graph Panel
  docs/sematic-ui.md
Labels: documentation

#672 Add minimally required resources to pre-install Helm hook
  helm/sematic-server/templates/configmap.yaml
  helm/sematic-server/templates/secret.yaml
  helm/sematic-server/templates/server-role-binding.yaml
  helm/sematic-server/templates/server-role.yaml
  helm/sematic-server/templates/serviceaccount.yaml
Labels: bug, infrastructure

#674 Fixes that ErrorBoundary error never dismisses.
  sematic/ui/packages/main/src/pipelines/Artifacts.tsx
Labels: bug, ui

#669 Use GiB instead of mixing 2**10 and 10**3 based calculations
  docs/ray.md
  sematic/plugins/kuberay_wrapper/standard.py
  sematic/plugins/kuberay_wrapper/tests/test_standard.py
Labels: bug, documentation

#663 Check and document libmagic dependency
  docs/container-images.md
  docs/future-algebra.md
  docs/get-started.md
  sematic/examples/testing_pipeline/BUILD
  sematic/examples/testing_pipeline/__main__.py
  sematic/examples/testing_pipeline/pipeline.py
  sematic/examples/testing_pipeline/resources/sammy.png
  sematic/types/types/image.py
Labels: documentation, compatibility, build

#673 Fix tuple summary
  sematic/types/types/tests/BUILD
  sematic/types/types/tests/test_tuple.py
  sematic/types/types/tuple.py
Labels: bug, types

#676 Make notifying about updates not fatal on failure
  sematic/api_client.py
  sematic/tests/test_api_client.py
Labels: reliability

#678 Release 0.27.0
  docs/changelog.md
  docs/get-started.md
  docs/upgrades.md
  helm/sematic-server/Chart.yaml
  sematic/versions.py
  sematic/wheel_constants.bzl
Labels: release

#680 Trivial doc update with user instructions
  docs/deploy.md
Labels: documentation

#682 Fixes bug when displaying duration for cloned run
  sematic/ui/packages/main/src/components/RunTime.tsx
Labels: bug, ui, usability

#689 Fixes a UI bug that the content of a table cell would explode the table width and disrupt column alignment
  sematic/ui/packages/main/src/components/CalculatorPath.tsx
  sematic/ui/packages/main/src/components/RunList.tsx
Labels: bug, ui

#683 Implement the components and styles for the new header bar
  sematic/ui/package-lock.json
  sematic/ui/packages/common/src/component/menu.tsx
  sematic/ui/packages/common/src/layout/Shell.tsx
  sematic/ui/packages/common/src/muitypes.d.ts
  sematic/ui/packages/common/src/static/fox.tsx
  sematic/ui/packages/common/src/theme/new/componnets.ts
  sematic/ui/packages/common/src/theme/new/index.ts
  sematic/ui/packages/common/src/theme/new/palette.ts
  sematic/ui/packages/common/src/theme/new/typography.ts
  sematic/ui/packages/storybook/.storybook/main.js
  sematic/ui/packages/storybook/package.json
  sematic/ui/packages/storybook/src/stories/Color.stories.tsx
  sematic/ui/packages/storybook/src/stories/Header.stories.tsx
  sematic/ui/packages/storybook/src/stories/Link.stories.tsx
  sematic/ui/packages/storybook/src/stories/Page.stories.tsx
  sematic/ui/packages/storybook/tsconfig.json
Labels: enhancement, ui

#688 Use URL parameter to construct redirects
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/artifacts.py
  sematic/api/endpoints/storage.py
  sematic/api_client.py
  sematic/plugins/abstract_storage.py
  sematic/plugins/storage/local_storage.py
  sematic/plugins/storage/memory_storage.py
  sematic/plugins/storage/s3_storage.py
  sematic/plugins/storage/tests/test_local_storage.py
  sematic/plugins/storage/tests/test_memory_storage.py
  sematic/plugins/storage/tests/test_s3_storage.py
  sematic/ui/packages/main/src/hooks/blobHooks.ts
Labels: tech debt

#668 New job storage queries & endpoints
  sematic/api/endpoints/events.py
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_runs.py
  sematic/api/server.py
  sematic/db/BUILD
  sematic/db/models/job.py
  sematic/db/queries.py
  sematic/db/tests/BUILD
  sematic/db/tests/fixtures.py
  sematic/db/tests/test_queries.py
Labels: enhancement, db

#694 Make local Server run with Python 3.10
  sematic/BUILD
  sematic/__init__.py
Labels: bug

#695 Fix matplotlib figures serialization
  sematic/types/types/matplotlib/figure.py
Labels: bug, types

#696 Fix corner case sqlite version comparison
  sematic/config/config.py
  sematic/tests/test_versions.py
  sematic/versions.py
Labels: bug, db, usability

#697 Use `Image` to support `matplotlib.figure.Figure`
  requirements/requirements.in
  sematic/types/types/image.py
  sematic/types/types/matplotlib/BUILD
  sematic/types/types/matplotlib/figure.py
  sematic/types/types/matplotlib/tests/BUILD
  sematic/types/types/matplotlib/tests/test_figure.py
  sematic/ui/packages/main/src/types/image.tsx
  sematic/ui/packages/main/src/types/matplot.tsx
  sematic/versions.py
Labels: ui, types

#699 Add more loggings for logs business
  sematic/ui/packages/main/src/hooks/logHooks.ts
  sematic/ui/packages/main/src/pipelines/ScrollingLogView.tsx
  sematic/ui/packages/main/src/tests/test_utils.cy.ts
  sematic/ui/packages/main/src/utils.tsx
Labels: bug, ui, housekeeping

#703 Ensure canceled Runs have and end time
  sematic/api/endpoints/resolutions.py
Labels: bug

#702 Show cases some of the new components
  sematic/ui/packages/common/src/component/GitInfo.tsx
  sematic/ui/packages/common/src/component/RunStateChips.tsx
  sematic/ui/packages/common/src/component/RunTree.tsx
  sematic/ui/packages/common/src/component/RunsDropdown.tsx
  sematic/ui/packages/common/src/component/TagsList.tsx
  sematic/ui/packages/common/src/context/SnackBarProvider.tsx
  sematic/ui/packages/common/src/pages/RunDetails/GitSection.tsx
  sematic/ui/packages/storybook/src/stories/Dropdown.stories.tsx
  sematic/ui/packages/storybook/src/stories/GitInfo.stories.tsx
  sematic/ui/packages/storybook/src/stories/RunStateChip.stories.tsx
  sematic/ui/packages/storybook/src/stories/Tags.stories.tsx
  sematic/ui/packages/storybook/src/stories/TooltipManager.stories.tsx
  sematic/ui/packages/storybook/src/stories/Tree.stories.tsx
Labels: ui, housekeeping
