Repository sematic-ai/sematic, pull requests merged in 2023-08, with the labels that each got.

#1023 Support filter runs using a relationship model field
  sematic/api/endpoints/request_parameters.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/db/models/BUILD
  sematic/db/models/run.py
Labels: enhancement

#1030 Better error message for Ray cluster from non-standalone function
  sematic/ee/tests/test_metrics.py
  sematic/future_context.py
  sematic/plugins/abstract_external_resource.py
  sematic/plugins/external_resource/timed_message.py
  sematic/resolvers/tests/test_worker.py
  sematic/resolvers/worker.py
  sematic/runners/cloud_runner.py
  sematic/runners/silent_runner.py
  sematic/runners/tests/test_silent_runner.py
Labels: bug, infrastructure, ee

#1031 Extend retry delay
  .circleci/retry
Labels: housekeeping, ci

#1034 Misc trivial fixes
  sematic/api/endpoints/tests/test_users.py
  sematic/api/server.py
  sematic/db/queries.py
  sematic/graph.py
  sematic/runners/local_runner.py
Labels: housekeeping

#1033 API capability of rerunning Pipelines with different Artifacts
  sematic/api/endpoints/resolutions.py
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/db/models/factories.py
  sematic/db/models/tests/test_factories.py
  sematic/db/tests/BUILD
  sematic/db/tests/fixtures.py
  sematic/examples/testing_pipeline/__main__.py
  sematic/examples/testing_pipeline/pipeline.py
Labels: bug, enhancement, scaling

#1036 Fixe a bug that could cause context menu missing.
  sematic/ui/packages/common/src/pages/RunDetails/FunctionSection.tsx
Labels: bug, ui

#1037 Make runner reentrant
  sematic/BUILD
  sematic/db/models/BUILD
  sematic/db/models/factories.py
  sematic/db/models/tests/test_factories.py
  sematic/db/tests/BUILD
  sematic/graph.py
  sematic/resolvers/BUILD
  sematic/resolvers/worker.py
  sematic/runners/cloud_runner.py
  sematic/runners/local_runner.py
  sematic/runners/tests/test_cloud_runner.py
  sematic/tests/test_graph.py
Labels: enhancement, usability

#1038 Release 0.34.0
  README.md
  docs/changelog.md
  helm/sematic-server/Chart.yaml
  sematic/ui/packages/common/src/pages/RunDetails/artifacts/OutputPane.tsx
  sematic/versions.py
  sematic/wheel_constants.bzl
Labels: release

#1040 Add a note related to uploading artifact to pypi.org
  README.rst
  developer-docs/README.md
Labels: documentation, housekeeping

#1042 Fix log view regression
  sematic/ui/packages/common/src/pages/RunDetails/logs/LogsPane.tsx
Labels: bug, ui, observability

#1045 Improve `sematic version` CLI
  sematic/api_client.py
  sematic/cli/BUILD
  sematic/cli/version.py
  sematic/tests/fixtures.py
  sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx
Labels: usability

#1048 Improve example refs in deploy docs
  docs/deploy.md
Labels: documentation

#1049 Release 0.34.1
  README.md
  README.rst
  docs/changelog.md
  helm/sematic-server/Chart.yaml
  sematic/versions.py
  sematic/wheel_constants.bzl
Labels: release

#1050 Add string parameter to Testing Pipeline
  sematic/examples/testing_pipeline/__main__.py
  sematic/examples/testing_pipeline/pipeline.py
Labels: enhancement, testing
