Repository sematic-ai/sematic, pull requests merged in 2023-07, with the labels that each got.

#954 Align DAG node handles and remove border of the handles
  sematic/ui/packages/common/src/pages/RunDetails/dag/CompoundNode.tsx
  sematic/ui/packages/common/src/pages/RunDetails/dag/LeafNode.tsx
  sematic/ui/packages/common/src/pages/RunDetails/dag/common.ts
  sematic/ui/packages/common/src/pages/RunDetails/dag/dagLayout.ts
Labels: bug, ui

#947 Some bug fixes for the new UI
  sematic/ui/packages/common/src/component/GitInfo.tsx
  sematic/ui/packages/common/src/component/Note.tsx
  sematic/ui/packages/common/src/component/RunStateChips.tsx
  sematic/ui/packages/common/src/component/RunsDropdown.tsx
  sematic/ui/packages/common/src/component/menu.tsx
  sematic/ui/packages/common/src/layout/TwoColumns.tsx
  sematic/ui/packages/common/src/pages/PipelineList/LatestRunsColumn.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunTabs.tsx
  sematic/ui/packages/common/src/pages/RunDetails/externalResource/index.tsx
  sematic/ui/packages/common/src/pages/RunDetails/logs/LogsPane.tsx
  sematic/ui/packages/common/src/pages/RunDetails/metricsTab/MetricsPane.tsx
  sematic/ui/packages/common/src/pages/RunDetails/metricsTab/index.tsx
  sematic/ui/packages/common/src/pages/RunDetails/pipelineMetrics/index.tsx
  sematic/ui/packages/common/src/pages/RunDetails/podLifecycle/index.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/CollapseableFilterSection.tsx
  sematic/ui/packages/common/src/pages/RunSearch/filters/StatusFilterSection.tsx
  sematic/ui/packages/common/src/pages/RunTableCommon/RunListEmptyState.tsx
  sematic/ui/packages/common/src/pages/RunTableCommon/filters/OwnersFilterSection.tsx
  sematic/ui/packages/common/src/theme/new/palette.ts
  sematic/ui/packages/common/src/typeViz/ArtifactVizTemplate.tsx
  sematic/ui/packages/storybook/src/stories/Header.stories.tsx
  sematic/ui/packages/storybook/src/stories/RunFilter.stories.tsx
Labels: bug, ui

#943 Deeplink search term in new UI
  sematic/ui/packages/common/src/hooks/runHooks.ts
  sematic/ui/packages/common/src/pages/RunSearch/SearchFilters.tsx
  sematic/ui/packages/common/src/pages/RunSearch/index.tsx
  sematic/ui/packages/common/src/pages/RunTableCommon/filters/SearchTextSection.tsx
  sematic/ui/packages/main/src/runs/RunIndex.tsx
Labels: enhancement, ui

#958 Fixes frequent updates on the artifact list
  sematic/ui/packages/common/src/pages/RunDetails/artifacts/InputPane.tsx
  sematic/ui/packages/common/src/pages/RunDetails/artifacts/OutputPane.tsx
  sematic/ui/packages/common/src/pages/RunDetails/artifacts/artifact.tsx
  sematic/ui/packages/common/src/typeViz/ArtifactVizTemplate.tsx
  sematic/ui/packages/common/src/typeViz/common.tsx
  sematic/ui/packages/common/src/typeViz/views/HuggingFaceReference.tsx
  sematic/ui/packages/common/src/typeViz/views/HuggingFaceStoredModel.tsx
Labels: bug, ui

#963 Make CI more robust
  .circleci/config.yml
Labels: housekeeping

#966 Fixes DAG zoom issue
  sematic/ui/packages/common/src/component/RunsDropdown.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/dag/CompoundNode.tsx
  sematic/ui/packages/common/src/pages/RunDetails/dag/LeafNode.tsx
  sematic/ui/packages/common/src/pages/RunDetails/dag/ReactFlowDag.tsx
Labels: bug, ui

#967 Fixes a bug about rerun request parameter
  sematic/ui/packages/common/src/hooks/resolutionHooks.ts
Labels: bug

#948 Have Cypress to test against the new UI
  sematic/ui/packages/common/src/component/Table.tsx
  sematic/ui/packages/tests/e2e/main.cy.ts
  sematic/ui/packages/tests/support/e2e.ts
Labels: ui

#962 Display avatar alongside user names
  sematic/ui/packages/common/src/component/Note.tsx
  sematic/ui/packages/common/src/component/UserAvatar.tsx
  sematic/ui/packages/common/src/component/UserMenu.tsx
  sematic/ui/packages/common/src/component/menu.tsx
  sematic/ui/packages/common/src/pages/RunDetails/NotesPane.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx
  sematic/ui/packages/common/src/pages/RunTableCommon/columnDefinition.tsx
  sematic/ui/packages/common/src/pages/RunTableCommon/ownerColumn.tsx
  sematic/ui/packages/common/src/utils/color.ts
  sematic/ui/packages/common/src/utils/string.ts
Labels: ui

#972 Fix Slack generated URL
  sematic/plugins/publishing/slack.py
  sematic/plugins/publishing/tests/test_slack.py
Labels: bug, observability

#971 Add images to summarization example
  sematic/examples/summarization_finetune/README.md
  sematic/examples/summarization_finetune/images/DAG.jpg
  sematic/examples/summarization_finetune/images/cnnSummary.jpg
  sematic/examples/summarization_finetune/images/dashboard.jpg
  sematic/examples/summarization_finetune/images/gradioSample.jpg
  sematic/examples/summarization_finetune/images/interactiveTranscript.jpg
  sematic/examples/summarization_finetune/images/runSearch.jpg
Labels: enhancement, examples

#970 Redact full DB URL from migration logs
  sematic/config/config.py
  sematic/db/migrate.py
Labels: bug, security

#973 Improve error handling for unschedulable resolutions
  sematic/abstract_future.py
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/resolutions.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/scheduling/job_scheduler.py
Labels: usability

#960 Fixes broken metrics link
  sematic/ui/packages/common/src/pages/PipelineRuns/PipelineInfoPane.tsx
  sematic/ui/packages/common/src/pages/RunDetails/contextMenus/PipelineSectionMenu.tsx
  sematic/ui/packages/common/src/pages/RunDetails/pipelineMetrics/BasicMetricsPanel.tsx
  sematic/ui/packages/common/src/pages/RunDetails/pipelineMetrics/index.tsx
Labels: bug, ui

#977 Fixes a datatime bug
  sematic/ui/packages/common/src/utils/datetime.ts
Labels: bug, ui

#903 Add migration to bring Postgres in parity with SQLAlchemy
  developer-docs/README.md
  sematic/db/migrations/20230706150252_pre_alembic_parity.py
  sematic/db/models/edge.py
  sematic/db/models/job.py
  sematic/db/models/mixins/has_user_mixin.py
  sematic/db/models/note.py
  sematic/db/models/resolution.py
  sematic/db/models/run.py
  sematic/db/schema.sql.sqlite
  sematic/metrics/tests/test_func_effective_runtime_metric.py
  sematic/metrics/tests/test_func_success_rate_metric.py
  sematic/metrics/tests/test_run_count_metric.py
  sematic/plugins/metrics_storage/sql/models/metric_label.py
  sematic/plugins/metrics_storage/sql/models/metric_value.py
  sematic/tests/test_abstract_system_metric.py
Labels: tech debt, db, reliability

#978 Add promotion banner to switch to new dashboard in old UI
  sematic/ui/packages/common/src/utils/FeatureFlagManager.ts
  sematic/ui/packages/main/src/Home.tsx
  sematic/ui/packages/main/src/components/PromotionBanner.tsx
  sematic/ui/packages/main/src/components/Shell.tsx
  sematic/ui/packages/main/src/components/SideBar.tsx
  sematic/ui/packages/main/src/pipelines/PipelineRunView.tsx
Labels: ui

#969 Update the docs to use the new "runner" classes and terminology.
  developer-docs/README.md
  docs/SUMMARY.md
  docs/advanced-features.md
  docs/api.md
  docs/cloud-runner.md
  docs/concepts.md
  docs/container-images.md
  docs/errors.md
  docs/first-pipeline.md
  docs/functions.md
  docs/future-algebra.md
  docs/github.md
  docs/glossary.md
  docs/local-execution.md
  docs/multiple-base-images.md
  docs/ray.md
  docs/real-example.md
  docs/slack.md
  docs/testing.md
  docs/type-support.md
  docs/upgrades.md
  sematic/examples/README.md
  sematic/examples/testing_pipeline/README.md
Labels: documentation, usability

#976 Add the Grafana panel to new dashboard as a plugin
  docs/developers/manual.md
  sematic/ui/package-lock.json
  sematic/ui/packages/addon-grafana/.eslintrc.js
  sematic/ui/packages/addon-grafana/package.json
  sematic/ui/packages/addon-grafana/src/GraphanaPanel.tsx
  sematic/ui/packages/addon-grafana/src/index.tsx
  sematic/ui/packages/addon-grafana/tsconfig.json
  sematic/ui/packages/common/package.json
  sematic/ui/packages/common/src/context/envContext.ts
  sematic/ui/packages/common/src/pages/RunDetails/RunTabs.tsx
  sematic/ui/packages/common/src/pages/RunDetails/atoms.ts
  sematic/ui/packages/common/src/pages/RunDetails/index.tsx
  sematic/ui/packages/main/package.json
  sematic/ui/packages/main/src/PluginsLoader.tsx
  sematic/ui/packages/main/src/addons/grafana/GrafanaPanel.tsx
  sematic/ui/packages/main/src/components/EnvironmentProvider.tsx
  sematic/ui/packages/main/src/index.tsx
  sematic/ui/packages/main/src/pipelines/RunTabs.tsx
  sematic/ui/packages/react-slot-fill/.eslintrc.js
  sematic/ui/packages/react-slot-fill/package.json
  sematic/ui/packages/react-slot-fill/src/Fill.ts
  sematic/ui/packages/react-slot-fill/src/Manager.ts
  sematic/ui/packages/react-slot-fill/src/Provider.ts
  sematic/ui/packages/react-slot-fill/src/Slot.ts
  sematic/ui/packages/react-slot-fill/src/index.ts
  sematic/ui/packages/react-slot-fill/tsconfig.json
Labels: ui

#979 Show user privacy settings in new dashboard
  sematic/ui/packages/common/src/component/TrackingNotice.tsx
  sematic/ui/packages/common/src/component/UserMenu.tsx
  sematic/ui/packages/common/src/utils/postHogManager.ts
  sematic/ui/packages/main/src/Home.tsx
  sematic/ui/packages/main/src/components/TrackingNotice.tsx
  sematic/ui/packages/main/src/index.tsx
Labels: ui

#982 Display cloned state icon for cloned runs
  sematic/ui/packages/common/src/component/RunStateChips.tsx
  sematic/ui/packages/common/src/component/RunStateText.tsx
  sematic/ui/packages/common/src/component/RunTree.tsx
  sematic/ui/packages/common/src/component/RunsDropdown.tsx
  sematic/ui/packages/common/src/pages/PipelineList/LatestRunsColumn.tsx
  sematic/ui/packages/common/src/pages/RunDetails/FunctionSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/dag/CompoundNode.tsx
  sematic/ui/packages/common/src/pages/RunDetails/dag/LeafNode.tsx
  sematic/ui/packages/common/src/pages/RunSearch/RunStatusColumn.tsx
  sematic/ui/packages/common/src/pages/RunTableCommon/columnDefinition.tsx
Labels: ui

#915 [1/N] Create Organizations data model
  sematic/api/BUILD
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/organizations.py
  sematic/api/endpoints/organizations_users.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_organizations.py
  sematic/api/server.py
  sematic/db/BUILD
  sematic/db/migrations/20230712105529_add_organizations_table.sql
  sematic/db/models/BUILD
  sematic/db/models/factories.py
  sematic/db/models/organization.py
  sematic/db/models/organization_user.py
  sematic/db/models/tests/BUILD
  sematic/db/models/tests/__init__.py
  sematic/db/models/tests/test_user.py
  sematic/db/models/user.py
  sematic/db/queries.py
  sematic/db/schema.sql.sqlite
  sematic/db/tests/BUILD
  sematic/db/tests/test_queries.py
Labels: enhancement, db

#917 [2/N] Add Organizations associations
  sematic/db/BUILD
  sematic/db/migration_utils.py
  sematic/db/migrations/20230706150252_pre_alembic_parity.py
  sematic/db/migrations/20230712121255_add_organizations_associations.py
  sematic/db/models/BUILD
  sematic/db/models/artifact.py
  sematic/db/models/mixins/BUILD
  sematic/db/models/mixins/has_organization_mixin.py
  sematic/db/models/resolution.py
  sematic/db/models/run.py
  sematic/db/schema.sql.sqlite
  sematic/plugins/metrics_storage/sql/models/BUILD
  sematic/plugins/metrics_storage/sql/models/metric_label.py
Labels: enhancement, db

#1003 Fix DB migration script for PostgreSQL
  sematic/db/migrations/20230712121255_add_organizations_associations.py
Labels: bug, db

#1002 Fixes an issue that local deployment cannot switch UI
  sematic/ui/packages/common/src/component/SettingsMenu.tsx
  sematic/ui/packages/common/src/component/UserMenu.tsx
  sematic/ui/packages/common/src/component/menu.tsx
  sematic/ui/packages/main/src/components/SideBar.tsx
Labels: ui, usability

#980 Support collapse all/expand all for artifact list
  sematic/ui/packages/common/src/context/artifactCoordinationContext.ts
  sematic/ui/packages/common/src/pages/RunDetails/artifacts/artifact.tsx
  sematic/ui/packages/common/src/pages/RunDetails/contextMenus/ArtifactMenu.tsx
  sematic/ui/packages/common/src/typeViz/ArtifactVizTemplate.tsx
Labels: ui

#1005 Enforce Runs fields selection
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/test_runs.py
Labels: bug

#1011 Breathing style for running state icon on the DAG view
  sematic/ui/packages/common/src/component/RunStateChips.tsx
  sematic/ui/packages/common/src/layout/Shell.tsx
  sematic/ui/packages/common/src/pages/RunDetails/dag/CompoundNode.tsx
  sematic/ui/packages/common/src/pages/RunDetails/dag/LeafNode.tsx
  sematic/ui/packages/common/src/theme/new/svgfilters.tsx
Labels: ui

#1017 Downgrade a spammy log message
  sematic/runners/state_machine_runner.py
Labels: observability, usability

#1012 Fix a bug in dag view expand/collapse event
  sematic/ui/packages/common/src/pages/RunDetails/dag/CompoundNode.tsx
Labels: bug, ui

#1016 Propagate Testing Pipeline raise retry probability to func
  sematic/examples/testing_pipeline/pipeline.py
Labels: bug, examples, testing

#1019 Add force clean
  sematic/db/models/tests/test_job.py
  sematic/scheduling/job_details.py
Labels: tech debt, infrastructure

#1022 Safer migration drop query
  sematic/db/migrations/20230706150252_pre_alembic_parity.py
Labels: db, reliability

#1020 Miscellaneous UI bug fixes
  sematic/ui/packages/common/src/component/RunReference.tsx
  sematic/ui/packages/common/src/pages/RunDetails/contextMenus/FunctionSectionMenu.tsx
  sematic/ui/packages/common/src/pages/RunDetails/contextMenus/RunSectionMenu.tsx
  sematic/ui/packages/common/src/pages/RunDetails/dag/ReactFlowDag.tsx
  sematic/ui/packages/common/src/pages/RunDetails/logs/LogsPane.tsx
  sematic/ui/packages/common/src/pages/RunDetails/podLifecycle/PodLifecycle.tsx
Labels: bug, ui

#1024 Fix a bug and pin libs for fine-tuning
  sematic/examples/summarization_finetune/requirements.txt
  sematic/examples/summarization_finetune/train_eval.py
Labels: bug, examples, build

#1007 Avoid Docker Build name collision with public repos
  sematic/plugins/building/docker_builder.py
Labels: bug, examples, security, reliability, build

#1009 New home page
  sematic/ui/packages/common/src/component/Table.tsx
  sematic/ui/packages/common/src/component/menu.tsx
  sematic/ui/packages/common/src/pages/GettingStarted/index.tsx
  sematic/ui/packages/common/src/pages/Home/Blog.tsx
  sematic/ui/packages/common/src/pages/Home/Community.tsx
  sematic/ui/packages/common/src/pages/Home/RunStateChipColumn.tsx
  sematic/ui/packages/common/src/pages/Home/blogs.json
  sematic/ui/packages/common/src/pages/Home/common.tsx
  sematic/ui/packages/common/src/pages/Home/index.tsx
  sematic/ui/packages/common/src/pages/Home/latestPipelines.tsx
  sematic/ui/packages/common/src/pages/Home/latestRuns.tsx
  sematic/ui/packages/main/src/index.tsx
  sematic/ui/packages/tests/e2e/main.cy.ts
Labels: enhancement, ui

#1008 Docker Build provide no-cache option
  docs/container-images.md
  sematic/cli/run.py
  sematic/plugins/abstract_builder.py
  sematic/plugins/building/docker_builder.py
  sematic/plugins/building/tests/test_docker_builder.py
Labels: enhancement, cli, usability, build

#1026 Release 0.33.0
  README.md
  README.rst
  docs/changelog.md
  helm/sematic-server/Chart.yaml
  sematic/examples/summarization_finetune/README.md
  sematic/examples/summarization_finetune/requirements.txt
  sematic/versions.py
  sematic/wheel_constants.bzl
Labels: release

#1028 Some UI improvements
  sematic/ui/packages/common/src/component/RunStateChips.tsx
  sematic/ui/packages/common/src/component/RunTree.tsx
  sematic/ui/packages/common/src/component/menu.tsx
  sematic/ui/packages/common/src/pages/RunDetails/dag/CompoundNode.tsx
  sematic/ui/packages/common/src/pages/RunDetails/dag/LeafNode.tsx
  sematic/ui/packages/common/src/theme/new/svgfilters.tsx
  sematic/ui/packages/storybook/src/stories/RunStateChip.stories.tsx
Labels: bug, enhancement, ui

#1029 Document pipeline-level metrics
  docs/metrics.md
Labels: documentation, ee
