Repository sematic-ai/sematic, pull requests merged in 2023-04, with the labels that each got.

#707 Ensure terminated Runs have an end time
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/local_resolver.py
Labels: bug

#704 Ensure DB schema dump
  .circleci/config.yml
  Makefile
  developer-docs/README.md
  docker/Dockerfile.ci
  docs/contribute-example.md
  sematic/db/migrate.py
  sematic/db/schema.sql.sqlite
Labels: housekeeping, db

#712 Use react hooks in story components
  sematic/ui/packages/common/src/reactHooks.ts
  sematic/ui/packages/storybook/src/stories/Tree.stories.tsx
Labels: housekeeping

#713 Allow setting debug flag in localstorage
  docs/changelog.md
  docs/developers/manual.md
  sematic/ui/packages/main/src/utils.tsx
Labels: ui, infrastructure

#701 Replace "External Job" with Job & add k8s job details
  docs/upgrades.md
  sematic/BUILD
  sematic/abstract_future.py
  sematic/api/endpoints/resolutions.py
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/api_client.py
  sematic/cli/tests/test_logs.py
  sematic/db/BUILD
  sematic/db/migrations/20230403153220_replace_external_jobs.sql
  sematic/db/models/BUILD
  sematic/db/models/job.py
  sematic/db/models/mixins/BUILD
  sematic/db/models/mixins/has_external_jobs_mixin.py
  sematic/db/models/resolution.py
  sematic/db/models/run.py
  sematic/db/models/tests/BUILD
  sematic/db/models/tests/test_run.py
  sematic/db/queries.py
  sematic/db/schema.sql.sqlite
  sematic/db/tests/test_queries.py
  sematic/log_reader.py
  sematic/resolvers/BUILD
  sematic/resolvers/worker.py
  sematic/scheduling/BUILD
  sematic/scheduling/external_job.py
  sematic/scheduling/job_details.py
  sematic/scheduling/job_scheduler.py
  sematic/scheduling/kubernetes.py
  sematic/scheduling/tests/BUILD
  sematic/scheduling/tests/test_job_scheduler.py
  sematic/scheduling/tests/test_kubernetes.py
  sematic/tests/BUILD
  sematic/tests/test_log_reader.py
  sematic/versions.py
Labels: infrastructure

#717 Docs: require k8s 1.23+ and separate ssl & ingress sections
  docs/deploy.md
Labels: documentation, infrastructure

#714 Ensure different users can rerun Resolutions
  docs/changelog.md
  sematic/api/endpoints/resolutions.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/__init__.py
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/api/tests/fixtures.py
  sematic/api_client.py
  sematic/db/models/factories.py
  sematic/db/models/mixins/has_user_mixin.py
  sematic/db/models/tests/test_resolution.py
  sematic/db/tests/fixtures.py
  sematic/examples/testing_pipeline/__main__.py
  sematic/resolvers/local_resolver.py
  sematic/resolvers/state_machine_resolver.py
Labels: bug, security, usability

#721 Fix display for run runtime when run is running
  sematic/ui/packages/main/src/components/RunTime.tsx
Labels: bug, ui

#722 Fixes log duplication issue
  sematic/ui/packages/common/src/utils/hooks.ts
  sematic/ui/packages/main/src/hooks/logHooks.ts
  sematic/ui/packages/main/src/tests/test_utils.cy.ts
  sematic/ui/packages/main/src/utils.tsx
Labels: bug, ui

#723 Fix composite type castability check for float
  sematic/types/types/float.py
Labels: bug, types

#725 Fix S3Location Dashboard link generation for directories
  sematic/examples/testing_pipeline/__main__.py
  sematic/examples/testing_pipeline/pipeline.py
  sematic/types/__init__.py
  sematic/types/types/aws/s3.py
  sematic/types/types/aws/tests/test_s3.py
  sematic/ui/packages/main/src/types/aws.tsx
Labels: bug, ui, types

#708 Implements new style Notes components
  sematic/ui/package-lock.json
  sematic/ui/packages/common/src/component/DateTime.tsx
  sematic/ui/packages/common/src/component/GitInfo.tsx
  sematic/ui/packages/common/src/component/NameTag.tsx
  sematic/ui/packages/common/src/component/Note.tsx
  sematic/ui/packages/common/src/component/PipelineTitle.tsx
  sematic/ui/packages/common/src/component/RunReferenceLink.tsx
  sematic/ui/packages/common/src/component/TagsList.tsx
  sematic/ui/packages/common/src/component/TooltipManager.tsx
  sematic/ui/packages/common/src/layout/ThreeColumns.tsx
  sematic/ui/packages/common/src/pages/RunDetails/NotesPane.tsx
  sematic/ui/packages/common/src/pages/RunDetails/SubmitNoteSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/index.tsx
  sematic/ui/packages/common/src/theme/new/componnets.ts
  sematic/ui/packages/main/package.json
  sematic/ui/packages/storybook/.storybook/main.js
  sematic/ui/packages/storybook/package.json
  sematic/ui/packages/storybook/src/stories/Notes.stories.tsx
  sematic/ui/packages/storybook/src/stories/Page.stories.tsx
Labels: ui

#724 Enable text selection on S3 buttons
  sematic/ui/packages/main/src/types/aws.tsx
Labels: enhancement, ui

#728 Make gevent monkey patch occur early
  BUILD
  sematic.pth
  sematic/BUILD
  sematic/__init__.py
  sematic/api/BUILD
  sematic/api/server.py
  sematic/cli/main.py
Labels: bug, build

#729 Fix an incorrect settings usage statement in the documentation
  docs/deploy.md
Labels: bug, documentation

#718 Enable reverse log traversal
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/cli/logs.py
  sematic/cli/tests/test_logs.py
  sematic/log_reader.py
  sematic/tests/test_log_reader.py
  sematic/ui/packages/main/src/Payloads.tsx
  sematic/ui/packages/main/src/hooks/logHooks.ts
Labels: observability

#733 Add line ids for log lines
  sematic/BUILD
  sematic/api/endpoints/tests/test_runs.py
  sematic/cli/tests/test_logs.py
  sematic/log_reader.py
  sematic/tests/test_log_reader.py
  sematic/ui/packages/main/src/Payloads.tsx
Labels: observability

#738 Release 0.28.1
  README.md
  docs/changelog.md
  helm/sematic-server/Chart.yaml
  sematic/versions.py
  sematic/wheel_constants.bzl
Labels: release

#739 Refactors devLogger creation
  sematic/ui/package-lock.json
  sematic/ui/packages/main/package.json
  sematic/ui/packages/main/src/utils.tsx
Labels: ui, housekeeping

#679 bazel: support insecure registry
  bazel/pipeline.bzl
Labels: enhancement, build

#744 Fix CircleCI GitHub badge
  README.md
Labels: bug, documentation, ci

#745 Remove unused image_tags param from sematic_pipeline
  bazel/pipeline.bzl
Labels: tech debt, build

#740 Improve release doc about setting up helm repo ahead of time
  developer-docs/README.md
Labels: documentation, housekeeping

#749 Update the Release Procedure to include updates in the release PR
  README.rst
  developer-docs/README.md
Labels: documentation, housekeeping

#730 Pod lifecycle history UI
  sematic/ui/packages/common/src/Models.ts
  sematic/ui/packages/main/src/Payloads.tsx
  sematic/ui/packages/main/src/hooks/podHistoryHooks.ts
  sematic/ui/packages/main/src/pipelines/RunTabs.tsx
  sematic/ui/packages/main/src/pipelines/external_resource/ExternalResource.tsx
  sematic/ui/packages/main/src/pipelines/pod_lifecycle/PodEventHistory.tsx
  sematic/ui/packages/main/src/pipelines/pod_lifecycle/PodLifecycle.tsx
  sematic/ui/packages/main/src/pipelines/pod_lifecycle/PodLifecycleEvent.tsx
  sematic/ui/packages/main/src/sockets.ts
Labels: enhancement, ui

#752 Add APIs to clean up orphaned jobs
  sematic/api/endpoints/resolutions.py
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/test_resolutions.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/api_client.py
  sematic/db/models/resolution.py
  sematic/db/queries.py
  sematic/db/tests/test_queries.py
  sematic/scheduling/BUILD
  sematic/scheduling/job_details.py
  sematic/scheduling/job_scheduler.py
  sematic/scheduling/kubernetes.py
Labels: infrastructure

#755 Support uninitialized Git repo rendering
  sematic/db/models/git_info.py
  sematic/utils/git.py
Labels: bug, ui

#736 Add cleaner CLI
  sematic/BUILD
  sematic/api/BUILD
  sematic/api/endpoints/auth.py
  sematic/api/server.py
  sematic/cli/BUILD
  sematic/cli/clean.py
  sematic/cli/main.py
  sematic/cli/tests/BUILD
  sematic/cli/tests/test_clean.py
  sematic/logging.py
Labels: enhancement, cli

#746 [1/N] Metrics support – `AbstractMetricsStorage` and `SQLMetricsStorage`
  sematic/abstract_plugin.py
  sematic/config/config.py
  sematic/db/migrations/20230419080554_add_metrics_table.sql
  sematic/db/schema.sql.sqlite
  sematic/metrics/BUILD
  sematic/metrics/__init__.py
  sematic/metrics/metric_point.py
  sematic/metrics/tests/BUILD
  sematic/metrics/tests/test_metric_point.py
  sematic/plugins/BUILD
  sematic/plugins/abstract_metrics_storage.py
  sematic/plugins/metrics_storage/__init__.py
  sematic/plugins/metrics_storage/sql/BUILD
  sematic/plugins/metrics_storage/sql/__init__.py
  sematic/plugins/metrics_storage/sql/models/BUILD
  sematic/plugins/metrics_storage/sql/models/__init__.py
  sematic/plugins/metrics_storage/sql/models/metric_label.py
  sematic/plugins/metrics_storage/sql/models/metric_value.py
  sematic/plugins/metrics_storage/sql/sql_metrics_storage.py
  sematic/plugins/metrics_storage/sql/tests/BUILD
  sematic/plugins/metrics_storage/sql/tests/test_sql_metrics_storage.py
  sematic/utils/BUILD
  sematic/utils/db.py
Labels: enhancement

#737 Extracts the text selection tool as a common utility
  sematic/ui/packages/main/src/hooks/textSelectionHooks.ts
  sematic/ui/packages/main/src/pipelines/pod_lifecycle/PodLifecycle.tsx
  sematic/ui/packages/main/src/types/aws.tsx
Labels: ui, housekeeping

#757 Migrating `inline=False` to `standalone=True`
  docs/SUMMARY.md
  docs/api.md
  docs/cloud-resolver.md
  docs/errors.md
  docs/glossary.md
  docs/multiple-base-images.md
  sematic/abstract_future.py
  sematic/calculator.py
  sematic/ee/plugins/external_resource/ray/cluster.py
  sematic/ee/plugins/external_resource/ray/tests/load_testing/pipeline.py
  sematic/examples/bazel/pipeline.py
  sematic/examples/cifar_classifier/pipeline.py
  sematic/examples/lightning_resnet/pipeline.py
  sematic/examples/mnist/pytorch/pipeline.py
  sematic/examples/retry/pipeline.py
  sematic/examples/testing_pipeline/__main__.py
  sematic/examples/testing_pipeline/pipeline.py
  sematic/future.py
  sematic/log_reader.py
  sematic/resolvers/cloud_resolver.py
  sematic/resolvers/state_machine_resolver.py
  sematic/resolvers/tests/test_cloud_resolver.py
  sematic/tests/test_calculator.py
  sematic/tests/test_future.py
Labels: documentation, tech debt, deprecation

#761 Make local storage location configurable
  docs/local-execution.md
  sematic/plugins/storage/local_storage.py
  sematic/plugins/storage/tests/BUILD
  sematic/plugins/storage/tests/test_local_storage.py
Labels: enhancement

#756 Implements the static Run details page center column
  sematic/ui/packages/common/src/component/DateTime.tsx
  sematic/ui/packages/common/src/component/Note.tsx
  sematic/ui/packages/common/src/component/Section.tsx
  sematic/ui/packages/common/src/component/menu.tsx
  sematic/ui/packages/common/src/layout/Shell.tsx
  sematic/ui/packages/common/src/layout/ThreeColumns.tsx
  sematic/ui/packages/common/src/pages/RunDetails/CenterPane.tsx
  sematic/ui/packages/common/src/pages/RunDetails/DebugSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/FunctionSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunTabs.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunTreeSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/index.tsx
  sematic/ui/packages/common/src/theme/new/componnets.ts
  sematic/ui/packages/storybook/src/stories/Tabs.stories.tsx
Labels: ui

#766 Remove front-end support for Matplotlib figures
  docs/changelog.md
  docs/upgrades.md
  sematic/ui/package-lock.json
  sematic/ui/packages/main/package.json
  sematic/ui/packages/main/src/types/Types.tsx
  sematic/ui/packages/main/src/types/matplot.tsx
Labels: ui, tech debt, types, deprecation

#767 Add Sematic Grafana dashboards as helm package
  developer-docs/README.md
  helm/sematic-grafana-dashboards/.helmignore
  helm/sematic-grafana-dashboards/Chart.yaml
  helm/sematic-grafana-dashboards/templates/sematic_jobs_dashboard_configmap.yaml
  helm/sematic-grafana-dashboards/templates/sematic_server_dashboard_configmap.yaml
  helm/sematic-grafana-dashboards/values.yaml
Labels: infrastructure

#770 Minor rewording of certain Dashboard labels
  sematic/ui/packages/common/src/pages/RunDetails/PipelineSection.tsx
  sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx
Labels: ui

#769 Add `LOCAL_STORAGE_PATH` to config map
  helm/sematic-server/templates/configmap.yaml
  helm/sematic-server/values.yaml
Labels: infrastructure

#764 [3/N] Metrics support – API endpoints
  sematic/BUILD
  sematic/abstract_system_metric.py
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/events.py
  sematic/api/endpoints/metrics.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_metrics.py
  sematic/metrics/tests/BUILD
  sematic/metrics/tests/__init__.py
  sematic/metrics/tests/fixtures.py
  sematic/plugins/abstract_metrics_storage.py
  sematic/plugins/metrics_storage/sql/tests/BUILD
  sematic/plugins/metrics_storage/sql/tests/test_sql_metrics_storage.py
Labels: enhancement, metrics

#774 Fix malformed API client error message
  sematic/api/endpoints/resolutions.py
  sematic/api_client.py
Labels: bug, usability

#773 [4/N] Metrics support – `FuncSuccessRateMetric`
  sematic/abstract_system_metric.py
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/metrics.py
  sematic/api/endpoints/runs.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_metrics.py
  sematic/api/endpoints/tests/test_runs.py
  sematic/metrics/BUILD
  sematic/metrics/func_success_rate_metric.py
  sematic/metrics/tests/BUILD
  sematic/metrics/tests/test_func_success_rate_metric.py
Labels: enhancement, metrics

#751 Add support for custom k8s security context; enable FUSE support
  docs/api.md
  helm/sematic-server/templates/configmap.yaml
  helm/sematic-server/values.yaml
  sematic/config/server_settings.py
  sematic/resolvers/resource_requirements.py
  sematic/resolvers/tests/test_resource_requirements.py
  sematic/scheduling/kubernetes.py
  sematic/scheduling/tests/test_kubernetes.py
Labels: enhancement, security, infrastructure

#778 [5/N] Metrics support – `FuncEffectiveRuntime` system metric
  sematic/api/endpoints/BUILD
  sematic/api/endpoints/metrics.py
  sematic/api/endpoints/tests/BUILD
  sematic/api/endpoints/tests/test_metrics.py
  sematic/metrics/BUILD
  sematic/metrics/func_effective_runtime_metric.py
  sematic/metrics/tests/BUILD
  sematic/metrics/tests/test_func_effective_runtime_metric.py
Labels: enhancement, metrics

#768 Fix kuberay autoscale
  docs/errors.md
  docs/ray.md
  sematic/ee/plugins/external_resource/ray/tests/load_testing/__main__.py
  sematic/ee/plugins/external_resource/ray/tests/load_testing/pipeline.py
  sematic/ee/plugins/external_resource/ray/tests/test_cluster.py
  sematic/ee/ray.py
  sematic/plugins/abstract_kuberay_wrapper.py
  sematic/plugins/kuberay_wrapper/standard.py
  sematic/plugins/kuberay_wrapper/tests/test_standard.py
Labels: enhancement, infrastructure

#772 Override can_continue_* flags
  sematic/log_reader.py
  sematic/tests/test_log_reader.py
Labels: tech debt

#780 Constrain plotly version for MNIST example
  sematic/examples/mnist/pytorch/requirements.txt
Labels: bug, examples, build
